README.md

I went through the instructions to build in my ubuntu VM. 
I made two small fixes to the instructions.
Without "sudo apt-get install zlib1g-dev" it will not find zlib.h and fails to compile.
I was not able to access the nvidia graphics card on my host machine from the VM, so I got a core dump when initializing OpenCL.  I guess I will be trying to build on windows next.

2 small fixes to ubuntu build instructions

---

training/tf/tfprocess.py

Following changes are commited:
1. Class `StatisticsCollector` is added to aggregate the accuracy/cost over batches.
(I usually use tf1.3, so I don't know whether tf1.4 has that function built-in)
2. `merge` & `FileWriter` is added to merge and save the summries
3. Summry parts are moved together
4. Factor 1/4 is moved to the defination of mse to make sure summries record the right value.
5. The model saving folder is changed to `leelamodel/leelaz-model` to avoid too many models in the main folder.
(I think the 2000-step check should be test part, if not please tell me.)
Summaries slow down the training, maybe we should save them every 100 steps 
I test the code on a Ubuntu 16.04

Merge and save summaries 

---

autogtp/main.cpp

Removed headers:
QtCore/QPair
QtCore/QVector
QRegularExpression
QUuid

Remove unused Qt headers from autogtp

---

autogtp/main.cpp

Can be enabled with -k, or --keep-sgf.
Also adds simple Qt-provided help and version options.
Fix #68

Add command line option to keep self-play .sgf files

---

src/GameState.cpp
src/GameState.h

This fixes the search getting slower with each move played due to large unecessary copies of the game state dominating the CPU time and using all the memory bandwidth.
Now it's as fast after 200 or 600 moves as in the opening.
This should help with #57 and #64 since (at least for me) it's now very fast and uses 100% GPU with only one or two instances.

Improve leelaz search performance 3-4x

---

src/UCTSearch.cpp

screenshot of hotspot profile: https://i.imgur.com/wNZVTNG.png
vtune shows 2.8% of time spent calculating PV for dump_stats
this is unneeded because autogtp runs leelaz in quite mode which suppress output of any extra stats.
before: 1302 moves = 611 ms/move (it would be nice if you would pull [PR113](https://github.com/gcp/leela-zero/pull/113))
after: 1601 moves = 602 ms/move

small optimization: avoid calculating PV in quiet mode

---

src/UCTNode.cpp
src/UCTNode.h
src/UCTSearch.cpp

Add a new function to get the "best" child (as determined by NodeComp)
this avoids sorting and linking all children x2
Intel VTune says impact is ~0.5% CPU

small optimization: simplify get_pv

---

autogtp/Production.cpp
autogtp/Production.h

Refactored pull request #95. Now checks the curl exit code too. The goal is to keep the clients running waiting for the server to come back if there is a server outage.
I removed the offline game playing from the commit to keep it smaller.
@marcocalignano can you take a look too?
fetchBestNetwork() is called even if fetchBestNetworkHash() reported that the hash has not changed to make sure that the file exists if there were previously any issues with the download.

Retry in case of network error instead of quitting

---

README.md
src/Im2Col.h
src/Network.cpp
src/OpenCL.cpp
src/OpenCL.h
src/config.h
src/half.hpp

This is a patch that uses half fp for the weights and the input/outputs.  They are converted immediately to fp32 once the GPU loads them, and all arithmetic is done in fp32.  This gives some (10~15%) performance improvement using a GTX1080.
Not sure if this is worth merging to master, but putting a pull request since it may worth thinking...

Changed NN in-memory representation from fp32 to fp16

---

autogtp/Production.cpp
autogtp/Production.h

Fixed compile time error because cmath isn't included (dependency for std::pow)

Update Production.cpp to fix dependency

---

training/tf/net_to_model.py
training/tf/tfprocess.py

This change allows creating a tensorflow checkpoint after initialization that uses an existing network file for weights.
First call "net_to_model.py <weights.txt>". This creates a checkpoint "leelaz-model-0", which can be used as a restore point in training using parse.py. If there's an error about assignment make sure that network file blocks/channels are same as in tfprocess.py.
Fixes #183.

Add functionality to start training from existing weights

---

src/GTP.cpp
src/Network.cpp
src/Network.h
src/OpenCL.cpp

the 1600 default is nice for understanding how long it might take for one move under normal circumstances.
But sometimes I want to run more (or less) when testing on different platforms (GTX 1080, my old 970, and historic 560) and when profiling test code. it would be nice not to have to modify Network.cpp as often as I find myself doing :)
-----

Add optional iterations parameter to netbench GTP command

---

training/tf/tfprocess.py

Change weight initialization from constant stddev to Xavier initialization. In my testing this converges much quicker at the beginning:
Decay value of 0.99 was too noisy in my opinion so I changed it to 0.999. Also added printing of the regularization term.
train_accuracy and train_mse can be calculated from single session.run() call.

Small tfprocess improvements

---

autogtp/Production.cpp
autogtp/Production.h
autogtp/main.cpp
resign_analysis/resign_analysis.py
src/GTP.cpp
src/Training.cpp
src/Training.h
src/UCTSearch.cpp

The first two commits just add resign_analysis.py and make changes to autogtp and leela src to support analyzing what the resign threshold should be. The last commit actually implements resignpct=10 in 90% of autogtp games. This should be pretty conservative because stats show there are only 2.13% incorrect resigns with this threshold, and we still get a 42% reduction in game length.
I wasn't sure how I should be generating random numbers, certainly the code I have in now is bad because it doesn't initialize the seed. Can someone show how I should do it? 
Here are the statistics using the latest net (22373747):
```
Resign rate: 0.50
Black won 467/516 (90.50%)
Incorrect uct resigns = 46/516 (8.91%)
Average game length = 285. Average game length with resigns = 2 (99.30% reduction)
Resign …
```

Set resignpct=10 in 90% of autogtp games

---

autogtp/Game.cpp

Before this change, "Score:" and "Winner:" were printed on one unique line in case of Resign.

AutoGTP: Line break after Score in case of Resign.

---

src/UCTNode.cpp

Dirichlet noise was only using the first value of the vector.
Policy priors should be re-normalized after removing illegal moves
so that they are on the same scale as dirichlet noise.
Fixes https://github.com/gcp/leela-zero/issues/282
I also have a debug version of the same thing here that prints more information.
https://github.com/killerducky/leela-zero/commit/c5801d3263bb45a8bbdaa0721eb59adc5d50800d
I took a position on move 293, the legal moves add up to 0.92 so the re-normalization isn't too bad there, but it might be worse in other positions, leading to the dirichlet noise overwhelming the policy priors.

Fix bug in dirichlet noise, re-normalize legal move policy priors.

---

FAQ.md

Fix hyperlink error under Tromp-Taylor rule part in FAQ markdown file, as it unexpectedly includes the Chinese characters in the rest of the paragraph.

FAQ: Fix hyperlink error in Tromp-Taylor rule explanation

---

autogtp/Game.cpp
autogtp/Game.h
autogtp/Job.cpp

Replaces default `Human` player name in sgf file with `Leela Zero <network>`.
Works with match and self-play games.
Currently white network name is not stored in the match sgf file making it hard to tell afterwards which one it was.

Fix white player name in sgf

---

src/Network.cpp
src/Network.h
src/config.h

Made it explicit that half-precision without OpenCL is unsupported.
Prevented the forward() function from being defined for non-OpenCL implementations
as it is causing compilation error (due to prototype mismatch) with USE_HALF

Fixed compile error with USE_HALF

---

src/GTP.cpp

Remove unused variable:
leela-zero/src/GTP.cpp:727:13: warning: unused variable ‘who_won’ [-Wunused-variable]

Remove unused variable

---

src/GTP.cpp
src/Network.cpp
src/half/half.hpp

CL2.hpp has warnings with gcc 5, 6, and 7.
```
In file included from OpenCL.h:27:0,
from UCTNode.cpp:42:
./CL/cl2.hpp:1831:5: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
const cl_type get() const { return object_; }
^~~~~
In file included from OpenCL.h:27:0,
from UCTSearch.cpp:40:
./CL/cl2.hpp:5857:63: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
typename std::enable_if<!std::is_pointer<T>::value, cl_int>::type
^
In file included from OpenCL.h:27:0,
from UCTSearch.cpp:40:
./CL/cl2.hpp:6157:22: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
vector<cl_int>* binaryStatus = NULL,
^
```
I have a [pull request](https://github.com/KhronosGroup/OpenCL-CLHPP/pull/34) open …

Cleanup gcc warnings

---

.gitignore
autogtp/Job.cpp
autogtp/Management.cpp
autogtp/main.cpp
msvc/VS2017/autogtp.vcxproj
msvc/VS2017/autogtp.vcxproj.filters
msvc/VS2017/leela-zero.vcxproj
msvc/leela-zero2017.sln

@qysnn 's fix <https://github.com/gcp/leela-zero/pull/313> for MSVC have been fully reviewed.
* Applied the same code change for both VC2015 and VC2017 (originally only VC2017)
* His code includes some irrelevent changes (FAQ, statistics etc), by rebase his commits I extracted out those changes. So this commit contains only MSVC changes
* He changed .gitignore and actually those ignores are already in a seperated folder under msvc
* The Qt Core dll copy task is missing timing specification, so it is actually being skipped. Specified this to be occur before "Compile". To test this, clone a new repository and build. The Qt dll shall appear in the output folder. 
Otherwise, his commit is very good and it worked from an clean repository.
**TODO**
We would like to have solutions to:
* download …

Qysnn's "minor" MSVC changes and some fix

---

src/KoState.cpp
src/KoState.h

This is also a small optimization (~1%) given frequency of copies (https://github.com/gcp/leela-zero/pull/89).
I have some future work hoping to convert the m_ko_hash_history from vector to set (or unordered_set) but that has proven to be complex

Cleanup unused m_hash_history

---

src/Makefile
src/TimeControl.cpp
src/TimeControl.h

Simplify duplicate code in `display_times` by adding `display_color_time(int color)`
Refactor `max_time_for_move(int color)` to avoid repeating some calculations.
smoked tested with
Unlimited
`echo -e "time_settings 0 1 0\nauto" | ./leelaz -w ../weights.txt`
Byo stones
`echo -e "time_settings 120 60 5\nauto" | ./leelaz -w ../weights.txt`
KGS style Fischer GO
`echo -e "kgs-time_settings byoyomi 20 6 4\nauto" | ./leelaz -w ../weights.txt`

TimeControl refactor

---

src/Network.cpp
src/Network.h
src/OpenCL.cpp

Saves few sqrt calls, but no observable performance change in practice due to batchnorm being so fast compared to convolutions.
This should improve reproducibility as OpenCL sqrt is guaranteed to be accurate only within 3 ULP, but std::sqrt precision is 0.5 ULP.

Precompute batchnorm weights

---

src/OpenCL.cpp

Fixes compilation of CPU-only leelaz after 9cf3126b2 commit

Do not process OpenCL.h when OpenCL is not used.

---

CMakeLists.txt
autogtp/README.md
autogtp/autogtp.pro

Qt is needed for autogtp only.
This patch removes the check from leelaz's CMakeLists.txt and adds it to the autogtp/autogtp.pro.

AutoGTP: check for a minimum supported Qt5 version

---

autogtp/autogtp.pro

lessThan function does numerical compare between variables, but failed on qt version "5.10".
btw, Qt 5.10 adds a new function 'versionAtLeast', but it's unavailable in older versions.

Qmake version checking fix

---

src/FastState.cpp
src/GTP.cpp
src/GameState.cpp
src/GameState.h
src/KoState.cpp
src/SGFTree.cpp
src/SGFTree.h

Instead of handling a resignation as a bit of a pass with some special handling, just set a specific flag in the GameState object.
This should allow removing some hacks in AutoGTP where it has to fix up our SGF files.
@marcocalignano @sethtroisi can you review?

Encode resignation separately.

---

src/GTP.cpp

game.get_last_move() no longer returns FastBoard::RESIGN on resigned games.

Fix the handling of resigned games in GTP.

---

training/tf/tfprocess.py

Change the avg_policy_loss et al to be average only over the step just
completed, rather than being an exponential average over all steps.
This is a more accurate estimate of the current losses.

Use windows average instead of exponential average for TF statistics.

---

src/FastBoard.cpp
src/FastBoard.h
src/FastState.cpp
src/FastState.h
src/FullBoard.cpp
src/GTP.cpp

Unused except by hidden GTP command "mc_score"
GTP command "final_score" is much more appropriate (and accurate).
`grep -ri "mc_score" .` matches nothing in src
Some testing was done with 
`(yes "go" | head -n150 && echo "mc_score" && echo "final_score") | ./leelaz -t 1 -s 123 -w ../weights.txt -p 50 --noponder`
to verify before / after

Remove unused monte carlo score estimate

---

src/FastState.cpp
src/FastState.h
src/KoState.cpp

Part of #528 maybe unnecessary (the `play_textmove` part) with this fix.
The current `FastState::play_move` function uses different logic to flip the m_tomove state for normal play and a pass. It sets the next player to move to be the opposite of the given player argument, this is correct but this code only apply to normal play.
For a pass play it delegate to `play_pass` without specifying the player. So it can only look at the current playing user, which is not necessary the same as the playing color. This may cause inconsistency but I don't know how can I trigger it.
Also, all other "State" classes (`KoState`, `GameState`) have a function `play_pass` with a player color argument, but `FastState` does not. So I decided to make it consistent rather than just add a single line before …

Fix FastBoard::play_pass consistency with similar logics

---

msvc/VS2015/leela-zero.vcxproj
msvc/VS2015/leela-zero.vcxproj.filters
msvc/VS2017/leela-zero.vcxproj
msvc/VS2017/leela-zero.vcxproj.filters

SMP.cpp was removed from src. This is to match up with the MSVC projects so it keep compiling.

MSVC update for removing SMP.cpp

---

src/GameState.cpp
src/GameState.h
src/Network.cpp
src/Network.h

Fixed version of https://github.com/gcp/leela-zero/pull/466, old version used INPUT_CHANNELS instead of INPUT_MOVES in gather_features.
---
It occurred to me that netbench is benchmarking a completely empty input so I also compared with some moves made, but it appears on my 970 to be ~equal
```
(yes "go" | 3head -n0 && echo "netbench 2000") | ./leelaz -t1 -s120 -w ../weights.txt -p 100 --noponder
=> before:  345 n/s  after: 352 n/s
(yes "go" | 3head -n30 && echo "netbench 2000") | ./leelaz -t1 -s120 -w ../weights.txt -p 100 --noponder
=> before:  346 n/s  after: 342 n/s
```
---
echo "auto" | ./leelaz -s 123 -t 1 -w ../autogtp/58da61769a5fb12ff555ee927f16b50d4c24de73a1170a85df1b0d2d706bdef3 -p 250 --noponder |& tee const_gamestate
echo "auto" | ./leelaz -s 123 -t 1 -w …

Change Network to use const GameState

---

src/Leela.cpp
src/NNCache.cpp
src/NNCache.h

Testing is documented [here (Google Sheets)](https://docs.google.com/spreadsheets/d/1KI6rRX_FAIHkq74p51weL2pRj2cMqlrZFCu6Ohh3kH8/edit#gid=785169179)
For people who use high playouts memory is already REALLY high (several gigs, thought I hope pull/567 helps with that) so the extra cache is unnoticed by them.
For people running autogtp performance will be the same (with size = 15,000 it's identical because no cache hit happens with age > 15,000) but 70 megs lighter. This allows for 40% more instances of leelaz to be run which is useful for people using cuDNN and large batch_sizes.
---
Spot testing
First 38 moves are the same when testing with
`(yes "go" | head -n60) | /usr/bin/time -v ./leelaz -t1 -s120 -w ../weights.txt -p 1000 --noponder |& tee smaller_cache`
Memory is reduced by ~70 megs …

Resize cache if max_playout is set

---

src/GameState.cpp

This assert fires when you run these commands:
```
play b q4
undo
genmove b
```
@sethtroisi do you see any other problems? From a quick test seems the rest of the code works.

Fix assert in GameState

---

src/UCTNode.h

We had the discussion on how to reduce memory footprint and have many good ideas, but this is a simple stopgap change which is better than nothing until we have something better.
(prior discussion : https://github.com/gcp/leela-zero/pull/567)
72 bytes -> 56 bytes, this is 2 cache lines vs. 1 cache line in many CPUs.

UCTNode field reorganization to optimize memory layout (attempt 2)

---

src/NNCache.cpp
src/NNCache.h
src/Network.cpp

I am not sure if this is a real bug or not, so I am posting a pull request anyway.  Please have a look and close if this seems to be a non-issue.
The concern here is that the prior lookup() does things this way:
1) acquire lock
2) search cache and find entry
3) return method, and release lock
4) create a copy, and return (this happens on Network::get_scored_moves)
If the entry gets deleted on insert() between 3) and 4) we can potentially segfault or have a corrupted table because the pointer is going to be deleted.
This patch tries to plug the hole by copying Netresult inside the lookup() method while holding the lock.

Removes a rare possible race condition on NNCache

---

src/Random.cpp

Fix for #592. Throgh it's very unlikely to happen, in a probability of around 1/2^64.

Fix Random::seedrandom to initilize xoroshiro128+ prng properly

---

autogtp/Game.cpp
src/GTP.cpp
src/GTP.h
src/Leela.cpp
src/SGFTree.cpp
src/TimeControl.cpp
src/TimeControl.h

This will help users reproduce games. Also helps address #416 by making short games unique as long as they used different random seeds or other command line arguments.
Time controls is a common source of confusion for users, and it's important to set correctly.
Example sgf:
```
(;GM[1]FF[4]RU[Chinese]DT[2017-12-18]SZ[19]KM[7.5]PB[Leela Zero 0.9 /home/ao]PW[Human]RE[W+7.5]
C[LeelaZ options: --noponder --playouts 1600 --weights weights --seed 15337825387906334875
LeelaZ time control: 3600s absolute]
;B[ap];W[pp])
```
Notice my user home directory is leaking in the PB field. I didn't change that code. The way autogtp works this won't happen because it uses the local directory. Also the printsgf GTP command is hard-coded to have the computer always white, human always black. Again it seems …

Print cfg_options_str and TimeControl in comment of sgf files.

---

src/FastBoard.cpp
src/FastBoard.h
src/FastState.cpp
src/FastState.h
src/GTP.cpp
src/GTP.h

Tested with
`(yes "go" | head -n100 && echo "final_status_list alive" ) | /usr/bin/time -v ./leelaz -t1 -s120 -w ../weights.txt -p 100 --noponder -g`

simplify FastBoard final_score and general cleanups

---

src/UCTNode.cpp
src/UCTNode.h
src/UCTSearch.cpp

Three minor fixes, found while testing very low playouts (`-t 1 -p 2 --noponder`).
- The PV was sometimes outputting an extra random move. 
- movecount>2 check causes it to output an extra random move when there is only 1 move searched. I think the !node->get_visits check is sufficient? Or is there some other corner case I didn't consider?
- the elapsed_centis check may not be needed at all, because the code below adds 1 to avoid the possibility of divide by zero. I left it in but changed it to check for it being less than negative one, although that should be impossible. The code as is suppresses the output for the testing I was doing since it ran fast enough to make elapsed_centis=0.
@roy7 this fixes a few issues you mentioned.

Minor fixes for dump_stats and get_pv.

---

src/GTP.cpp
src/GTP.h
src/Leela.cpp
src/UCTSearch.cpp
src/UCTSearch.h

When this option is used, include past search results and stop the search when the sum of the children's visits reaches --visits.
I'm re-running the tournament to ensure we still get an Elo improvement on same CPU usage. 
I made it so ttable_sync_all_children is only called when the --visits argument is used. This way the behavior when using --playouts doesn't change. I also verified the code in Training::record that does sum_visits always gets exactly --visits.

Add new option --visits

---

src/FastBoard.cpp
src/FastState.h
src/GTP.h
src/KoState.cpp
src/OpenCL.cpp
src/OpenCL.h
src/SGFParser.h
src/SGFTree.cpp
src/SGFTree.h
src/Training.h
src/UCTNode.cpp
src/UCTSearch.cpp
src/Utils.cpp

`grep -rh '^#include <c[a-z]*>' *.cpp *.h | sed -e 's/.*<c//' -e s'/.$//' | sort -u | xargs -I{} sh -c 'echo "$(grep -riho "include <c{}>" *.cpp *.h | wc -w) c{} vs $(grep -riho "include <{}.h>" *.cpp *.h | wc -w) {}.h"' | sort -rn`
14 cassert vs 12 assert.h
12 cstdint vs 2 stdint.h
6 cstdlib vs 0 stdlib.h
6 cmath vs 0 math.h
6 chrono vs 0 hrono.h
6 cctype vs 0 ctype.h
4 cstdio vs 6 stdio.h
4 climits vs 0 limits.h
2 ctime vs 0 time.h
2 cstddef vs 12 stddef.h
afterwards I found one extra instance (of stdarg.h) with
`grep -rh '^#include .*\.h>' *.cpp *.h`
If you prefer the .h version I can convert all existing <cLIB> version to <LIB.h> I just prefer consistence

replaced #include <lib.h> with equivilant <clib>

---

src/GTP.cpp
src/UCTSearch.cpp
src/UCTSearch.h

New resign logic discussed in https://github.com/gcp/leela-zero/issues/622
Leelaz doesn't resign before move 90 (92?).
For games with handicap reduce handicap rate even more for moves 90 to ~215.
[Old graph of resign pct vs move number](
https://docs.google.com/spreadsheets/d/1AIGYObGCGWadcdWwN1ceMuPd_qu1hyQd2tD8QzSsGV8/edit#gid=1843999952)

new resign logic for handicap threshold

---

src/FastState.cpp
src/FullBoard.cpp
src/FullBoard.h
src/GTP.cpp
src/Zobrist.cpp
src/Zobrist.h

Fixes issue #576.
Definition of m_komove changed slightly to be only set to the vertex if that vertex is actually a ko. That part used to be lazy calculated in is_move_legal. I think that extra code could be removed now from is_move_legal but I need to check weird cases like same color gets to genmove commands. Maybe we don't care about that.
Reproduce bug:
`rm master.log; cat testgtp.txt | $lzmaster -w latest.txt -p 10 --noponder -l master.log
`
Verify fix:
`rm test.log; cat testgtp.txt | ./leelaz -w latest.txt -p 10 --noponder -l test.log
`
[testgtp.txt](https://github.com/gcp/leela-zero/files/1629027/testgtp.txt)
[master.log](https://github.com/gcp/leela-zero/files/1629028/master.log)
[test.log](https://github.com/gcp/leela-zero/files/1629029/test.log)
I will to add a few more tests …

Fixes to m_hash and m_ko_hash.

---

autogtp/Management.cpp

In fallback case, saved bin will be broken since `-s ` is also saved
@marcocalignano Please review

Autogtp: Fix random seed saving in fallback case

---

src/OpenCL.cpp

Batch norm is the only remaining kernel that requires number of channels to be divisible by 8. Removing the fixed local size allows using network with any amount of filters. I used the odd sizes for testing net2net, but maybe they are useful in other tests too.
This kernel is actually only run once for the input convolution. Other batch norms are calculated inside the Winograd output transformation and this whole kernel could be removed with some refactoring.
Effect to performance is less than what I'm able to benchmark accurately.

Remove filter size restriction in batch norm

---

training/tf/net_to_model.py
training/tf/tfprocess.py

If the filters/blocks are different and the replacement is tried it will fail with hard to understand error message. This commit adds a clearer error message.

Check that filters/blocks match in net_to_model

---

src/UCTSearch.cpp

if get_first_child is nullptr then line 224 would have segfaulted
I don't believe line 228 ever gets invoked (we should always have at least one visit per the structure of UCTSearch::think)
Even if we did were trying to decide on the best move with zero playouts I don't see why that special case would get to overrides the pass/nopass/dumppass behavior

cleanup get_best_move

---

src/GTP.cpp
src/GameState.cpp
src/UCTNode.cpp
src/UCTNode.h
src/UCTSearch.cpp
src/UCTSearch.h

UCTSearch originally took a reference to the current game state. Tree
reuse made it keep its own copy, which is now causing problems to keep
in sync. Revert that and make it take a reference again. We copy the
last GameState at the end of the search and use the copy to find back
the right UCTNode root at the beginning of the next search.
Fixes issue #690.

Make UCTSearch take a reference to the game state.

---

src/FastState.cpp
src/FastState.h
src/FullBoard.cpp
src/GTP.cpp
src/GameState.cpp
src/GameState.h
src/KoState.cpp
src/KoState.h
src/UCTSearch.cpp

IMO this is more generic code and
We're able to removing the nearly identical play_pass from FastState.cpp

Change play_move to handle FastBoard::PASS

---

src/CL/cl2.hpp

Got this fixed [upstream](https://github.com/sethtroisi/OpenCL-CLHPP/commit/66358621ece5197f90cc457a08d629ac63559e73)
Generated verified this was the only diff with
curl https://raw.githubusercontent.com/sethtroisi/OpenCL-CLHPP/master/input_cl2.hpp > CL/cl2.hpp

update cl2.hpp which fixes gcc warning

---

src/Leela.cpp

When file input is used with Leela, and leelaz exits normally the prompt ("Leela: ") without a newline will often be the last output. this shifts the bash prompt and if you press up for the last command and that command is longer than one line it will put [bash in a weird state](https://askubuntu.com/a/24422/767394) because it thinks the command should wrap at a different place.
This prints a newline before exiting in some cases
|command|behavior|
|---|---|
| exit | unchanged (no newline) |
| runtime error | unchanged |
| quit | print an extra, unneeded newline |
| pipe | print a newline for "Leela:" line|
| file redirect | print a newline for "Leela:" line|
This does print the extra newline even in GTP mode but I'm assuming a training newline at EXIT isn't going to break anything (I did …

add newline on normal exit

---

src/UCTNode.cpp
src/UCTNode.h
src/UCTSearch.cpp
src/UCTSearch.h

**Improvements**
* Can now find new_root at >1 depth,
* Uses m_rootstate history to find moves
* Prints stats if #ifndef NDEBUG
* Supports 100% tree reuse after a single undo
tested with 
make -j8 debug
echo -e "time_settings 0 8 1\ngo\ngo\ngo\ngo\nkomi 8\ngo\nclear_board\ngo\nplay white D4\nplay black R4\nplay white D16\ngo\nundo\ngo" | ./leelaz -w ../weights.txt -s 123 -t 1; echo
|command|explanation|output|
|---|---|---|
|go|no tree reuse on first move||
|go||Leela: update_root Q16, 2857321 -> 423165 nodes (14.8% reused)|
|go||Leela: update_root D4, 2724778 -> 936392 nodes (34.4% reused)|
|go||Leela: update_root R4, 2865117 -> 959579 nodes (33.5% reused)|
|komi 8|||
|go|no reuse because of komi changed||
|clear_board|||
|go|no tree reuse because of clearing board||
|play white D4|| …

Refactor find_new_root

---

src/Network.cpp

Newer networks have zero biases since they are cancelled by the batchnorm.
However some older networks, such as the 6x128 human best network have non-zero
biases. Biases can be moved to batchnorm means to fix the output.
This fixes the mysterious different output of human best 6x128 network with Winograd convolution. Now the heatmap matches the previous implementation.

Fix ignored biases

---

src/Network.cpp
src/Network.h
src/OpenCL.cpp
src/OpenCL.h
src/OpenCLScheduler.cpp
src/OpenCLScheduler.h

Currently getting data out of the GPU is the biggest bottleneck. This transfer can be made faster with pinned (mapped) memory. Just replacing the transfer gives about 6 % performance increase in netbench.
I also moved the 1x1 convolutions of the output heads to GPU to reduce the amount of memory that needs to be moved. That increased performance gain to 15 % compared to the original.
```
Current:
10000 evaluations in 14.40 seconds -> 694 n/s
Pinned memory:
10000 evaluations in 13.48 seconds -> 741 n/s
Pinned memory + OpenCL head convolutions:
10000 evaluations in 12.41 seconds -> 805 n/s
```
It still seems that the memory transfer is limiting the performance. If I comment it out I get `10000 evaluations in 11.47 seconds -> 871 n/s`. Host -> device memory transfer doesn't seem to be as …

Use pinned memory for device -> host transfers

---

src/Network.cpp

We could report a self check failure if two very small values differed
in sign, which makes no sense.
Fixes issue #818.

Don't check sign differences near zero.

---

training/tf/tfprocess.py

With the wrong capitalization, Tensorboard outputs the "Policy loss" (lowercase L) onto a different scalar chart than "Policy Loss". Instead, the policy loss logs for both test and train should be output onto the same chart, as is already the case for the Tensorboard MSE Loss chart.

Tensorboard tag: Must capitalize the L in "Policy Loss"

---

src/UCTNode.cpp
src/UCTNode.h
src/UCTSearch.cpp

if `UCTSearch::play_simulation` expands a leaf node it counts it as a visit. 
if the root node is a leaf node it gets expanded in `UCTSearch::think` but isn't counted as a visit.
I unified this by counting the initial "visit" in `UCTSearch::think` which is a much smaller change because it only happens when playouts is TINY or when opponent play weird moves that weren't expected.
After this behavior is unified I'll write a 2nd change ([preliminary draft](https://github.com/sethtroisi/leela-zero/compare/c__tt_cleanup...sethtroisi:c__tt_cleanup_v2)) to not count initial expansion as visits per "Mastering the game of Go" which says "Edge edge traversed in the simulation is updated to increment its visit count" ie leaf nodes have zero visits but this requires updating `get_pv` and …

Small cleanup to visit counting

---

msvc/VS2015/autogtp.vcxproj
msvc/VS2015/autogtp.vcxproj.filters
msvc/VS2017/autogtp.vcxproj
msvc/VS2017/autogtp.vcxproj.filters

Fixes issue #828 
Tested on Visual Studio 2017 only but hopefully it works on Visual Studio 2015 too.
By the way, I used to have around 29-30 warnings when building with VS2017 before. With the latest changes, however, there are no warnings at all now, so, that's great.
This is my first time making a pull request, so, please tell me if I need to fix anything.

Fixing build with Visual Studio

---

src/Random.cpp
src/Random.h
src/Tuner.cpp
src/UCTNode.cpp
src/tests/utils_unittest.cpp

None of has real impact (assuming this doesn't break things) because PRNG is good enough for all our uses (Zobrist and sampling)
* Added comments about inclusive vs exclusive
* `uniform_int_distribution` better handles the one arg case.
`randuint16_t(60000)` was twice as likely to choose some numbers (0, 10, 21, 32, ...) as others.
* Replaced the only use of randflt with randfix
News tests can probabilistic fail (they choose a random seed).
**Pros**
* The failure rate is very low (4 in 10,000 theoretically and ~1 in 1,300 in practice).
* Helps detect bad PRNG
* Avoids the problem where everything is a mock and nothing is actually tested
**Cons**
* Possible that if PRNG is bad it will fail rarely but often enough to cause confusion
---
**Testing**
No impact on performance
``` …
```

Make use of <random> in Random.cpp + add tests

---

src/GTP.cpp
src/GTP.h
src/Leela.cpp
src/UCTSearch.cpp
src/UCTSearch.h

Stop thinking when it's unlikely for the best move to be overtaken. A simple first step for #788.
I only did a very quick sanity check on this, will test more later. Looking for feedback on switch name etc.
For --visits and --playouts I think it should be impossible for this code to mistakenly stop thinking too early, assuming TM_MARGIN of 0.9f is much larger than virtual loss and other thread weirdness. For time controls there could be issues if the computer load changes while thinking, but that doesn't seem like a big problem to me.

Add new option --timemanage.

---

src/Training.cpp

In validation set change CHUNK_SIZE was decreased to 32 causing the debug data to be split in many chunks since it called `OutputChunker.append` for each line. This change adds temporary string variable so that append is only called once.

Fix debug data chunking

---

src/GTP.cpp
src/UCTNode.cpp

This is a fpu reduction method that seems like it is as strong as parent's net_eval for weak network while being as strong as flat fpu reduction of 0.22 for strong networks.

modify fpu reduction depending on visited policy

---

README.md
src/UCTSearch.cpp

Wait for at least 1 second and 100 playouts so we get a reliable playout_rate.
roy7 saw this on his machine. Most moves he gets over 2000n/s. But on the very first playout the measured average is much lower. This fix adds a minimum time and playout count so we have a reliable average playout_rate to work with.
Example of the problem: http://termbin.com/9zrg
After only 1st playout it measured 33n/s instead of 2000n/s, and triggered the stop.
```
Thinking at most 25.0 seconds...
NN eval=0.492506
25.0s left
Stopping early.
G14 ->    1483 (V: 51.69%) (N: 44.95%) PV: G14 H11 J13 K13 J18 H18 K17 J16 H17 J19 K18 G17 H16 H15 G16 G15 F16 F14 J15 K15 F15
H11 ->     211 (V: 50.01%) (N:  8.07%) PV: H11 G14 H14 G15 F14 H10 G10 F11 H9 H12 H13
1996 visits, 359952 nodes, 1 playouts, 33 n/s
= G14
```

Small Timemanage fix.

---

AUTHORS

I was listed twice in AUTHORS both by my nick and by my proper name.

Duplicate entry for nick and proper name in AUTHORS

---

src/UCTNode.cpp

on line 344 `value == best_value` (for the node that's ultimately selected) about 1 in every 500 playouts.
This means that 1 in 1000 playouts play_simulation explores the 2nd best child.
With the change `puct` and `value` are now doubles and at 100,000 playouts I see no identical `best_value` (if you want to test this you can look at [this branch](https://github.com/gcp/leela-zero/compare/next...sethtroisi:v__uct_work_debug?expand=1)
**pros**
*  More correctly evaluates UCT value
*  Fixes 1 in 1000 exploration of 2nd best child
*  Makes `uct_select_child` not dependent on internal sort order
**cons**
*  double calculation is slightly more expensive (In testing this is <0.5%)
*  2nd best child is very close to 1st best child so eval isn't wasted just not technically correct
----- …

change UCT numerator to double

---

src/UCTNode.cpp
src/UCTNode.h
src/UCTSearch.cpp

Rather than have each child store its parent's net eval, have every node store the net eval of its own game state. No change in behaviour (verified with --benchmark).

Simplify m_init_eval to m_net_eval

---

src/UCTNode.cpp

See also https://github.com/glinscott/leela-chess/pull/72
I guess we avoided this issue because LZ's initial random net was very small. @Ttl showed a new random 5x32 net was not so uniform, but the heatmap of the first LZ 1x8 random net looked fine (totally uniform policy, near 50% value).
But this code seems like a good safeguard.

Normalize policy to uniform when the sum is denorm.

---

README.md
training/tf/parse.py

Refactor the training input pipeline.
1. Introduce a binary format (v2).
2. Use the v2 format for the shuffle buffer (shrinks RAM by ~2x)
3. Support for loading v2 format off disk (much faster to parse)
4. Amend test to be full end-to-end test, including worker interfaces.
5. Add benchmark for the tensorflow frontend.
6. Change worker->main process communication to be fixed size binary format instead of protobuf.
Net result is that the pipeline now saturates at about 45,000 moves/sec into tensorflow (aka ~88 batches/sec with n=512).

V2pipeline

---

README.md

This doesn't install unnecessary Boost libraries, which right now would take up 200 MB of space.

Minimum necessary Boost installation

---

msvc/VS2015/leela-zero.vcxproj
msvc/VS2015/leela-zero.vcxproj.filters
msvc/VS2017/leela-zero.vcxproj
msvc/VS2017/leela-zero.vcxproj.filters
src/Makefile
src/UCTNode.cpp
src/UCTNode.h
src/UCTNodeRoot.cpp

UCTFullNode contains all the methods that should/are only called on root nodes (kill_superkos, dirichlet_noise, randomize_first_proportionally). I'm slightly prefer the name "UCTRootNode" but I went with the project convention.
Pros
* UCTNode was getting quite large: 450 lines with 7 helper methods used once each from UCTSearch
* UCTFullNode code is UCTSearch specific and disjoint generally disjoint from UCTNode logic.
* Helpful for small_node pull (UCTFullNode can have the invariant that it's fully expanded)
Cons:
* UCTFullNode doesn't have additional data, in practice every UCTNode is actually a UCTFullNode.
* dump_stats  (useful when debugging) can only be called on UCTFullnode and will require a static_cast when debugging.
* std::unique_ptr don't support automatically casting to a …

Split UCTNode into UCTFullNode and UCTNode

---

src/UCTSearch.cpp
src/UCTSearch.h

Calculates average node depth, max depth, number of "leaf nodes" (nodes  more than 1 children), average number of children.
I added this to the end of dump_stats which prints at the end of think (so 2 extra lines per move)
Example output of benchmark, weights = b8adb7da (my personal favorite network)
`./leelaz -w weights --benchmark --noponder -p 1000`
```
Thinking at most 2678400.0 seconds...
NN eval=0.476396
D4 ->     313 (V: 50.26%) (N: 28.82%) PV: D4 D16 Q4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 R3 R4 Q3 P3 P2
Q4 ->     262 (V: 50.15%) (N: 25.25%) PV: Q4 D4 D16 R3 Q3 R4 R5 S5 S6 R6 Q5 S7 S4 T6 S3 C17 D17 C16 C15
D16 ->     250 (V: 50.24%) (N: 23.48%) PV: D16 Q4 D4 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C18 B18 C3 D3 C4
R4 ->      38 (V: 50.03%) (N:  3.76%) PV: R4 D4 D16 C17 D17 …
```

Add tree_stats to compute stats search tree

---

src/UCTNode.cpp
src/UCTNode.h
src/UCTSearch.cpp
src/UCTSearch.h

This generalizes the time management code such that it stops visiting any root child the moment it can no longer overtake the current best. Might provide a slight speed and/or performance boost.

Stop visiting doomed root children

---

README.md

It's easy to overlook the existence of the other readme, as what happened [here](https://www.reddit.com/r/cbaduk/comments/83a4jl/i_need_help_to_get_automatic_leela_zero_training/).

README: explicit link to autogtp's readme.

---

src/UCTSearch.cpp

Fixes to prevent pondering from running forever. Stop after m_maxvisits or m_maxplayouts. I think this is probably close to what a user expects when they use `-v` but leave pondering on. Without `-v` in normal cases it will stop on MAX_TREE_SIZE. But in some endgame cases the tree is not growing, so this change also prevents overflowing m_visits in nodes. See more here https://github.com/gcp/leela-zero/issues/994#issuecomment-371999812
I just picked numeric_limits::max/2, that should be more than enough I think. Another possibility is subtract something like 1000 from max just to prevent multiple threads from causing it to go past max.
This fixes one possible cause for #994. I think we need to do something more dynamic about MAX_TREE_SIZE to prevent using all memory and slowing a user's …

Fixes to prevent pondering from running forever.

---

training/tf/parse.py

After fixing the FileDataSrc training for leela-chess seems correct again. I'll post some results in the morning. In any case the bug exposed here is definitely a problem that needs to be resolved for V2.

bugfix FileDataSrc

---

training/tf/parse.py

Unit test currently fails, but will pass after #1032 is pulled.

Add a unittest for the FileDataSrc class.

---

autogtp/Job.cpp
autogtp/Management.cpp
autogtp/Management.h
autogtp/main.cpp

`autogtp` now saves all networks in a subdirectory `networks`. If the option `--erase` (`-e`) is active then the old best network and the old networks used for matches are deleted so that in that directory there are at most 3 networks.
If you use the stop-resume option (`q+Enter`) to update to this version you have to manually copy the network used by the saved games. To do this look into the files `storefile*` and check the lines starting with 
`network` `firstNet` `secondNet` and copy them in the new directory networks.
If you are under Linux you can use the following command to find the networks you need:
`grep -e network -e firstNet -e secondNet storefile*  | awk '{print $2}' | sort | uniq`

autogtp: clean up networks when they are not needed any more

---

src/Network.cpp

Main benefit is from `winograd_transform_in()` by reading the input into a zero padded array for each channel rather than each block (of each channel). I'll see if I can do something similar for opencl (outside of this pr and I may ask for help if I get stuck).
CPU only:
`$ time ./leelaz -w ed26f634 -t 1 --noponder --benchmark -p 10000`
was:
`10001 visits, 3506140 nodes, 10000 playouts, 53 n/s`
`real    3m11.195s`
now:
`10001 visits, 3506140 nodes, 10000 playouts, 59 n/s`
`real    2m51.633s`
With GPU and `-p 100000`:
was:
`100001 visits, 34117003 nodes, 100000 playouts, 491 n/s`
`real    3m27.845s`
now:
`100001 visits, 34117003 nodes, 100000 playouts, 492 n/s`
`real    3m26.939s`

Optimised various parts of Network

---

src/UCTNode.cpp

For unvisited nodes the score is proportional to the calculated value. Therefore for the unvisited nodes the best score can be found whilst counting the parent visits and used once to calculate the best value for those nodes. This then allows the second loop to only process nodes that have visits > 0.
$ time ./leelaz -w weights -t 1 --noponder -p 100000 --benchmark
Before:
100001 visits, 34766701 nodes, 100000 playouts, 950 n/s
real    1m48.873s
After:
100001 visits, 34766701 nodes, 100000 playouts, 960 n/s
real    1m47.830s
Edit: with latest next and 75603ad2
Before:
100001 visits, 34320429 nodes, 100000 playouts, 458 n/s
real    3m41.455s
After:
100001 visits, 34320429 nodes, 100000 playouts, 460 n/s
real    3m40.657s

Reduced processing of unvisited nodes in UCTNode::uct_select_child()

---

src/Network.cpp
src/Network.h

As these functions are never called with reused vectors, this change should be a no-brainer in terms of readability, safety and usability.

Remove out-parameters from network functions.

---

training/tf/chunkparser.py
training/tf/parse.py
training/tf/tfprocess.py
training/tf/v2_write_training.py

Add support for mini-batches larger than GPU RAM size.
1. Minor bugfix to use correctly use WEIGHTS instead of REGULARIZATION_LOSSES.
2. Refactor out statistics into a separate class.
3. Refactor out timing into a separate class.
4. Refactor out batch_norm
5. Refactor out measuring loss
6. Drop use of tf.Dataset: instead, feed batches directly into placeholders.  (Simplifies code)
7. Run 'while True' loop inside tfprocess.py instead of parse.py
8. Split out training into 'compute_gradient' + 'apply gradient'.
9. Accumulate gradient until a full macrobatch has been processed before applying.
(NB: This is based on #959)
Should be fully backward compatible with previous iterations of training scripts.

Add support for training on mini-batches larger than GPU RAM size.

---

training/tf/average_weights.py
training/tf/net_to_model.py
training/tf/tfprocess.py

Implements weight averaging method in: https://arxiv.org/abs/1803.05407. Outputs file called `leelaz-<number of nets in average>-<training steps>.txt` during the training. average_weights.py can be used also as a stand-alone program to average existing weights.
Average weight file is not restored when restoring from the model.

Implement stochastic weight averaging

---

src/UCTNode.cpp
src/UCTNode.h
src/UCTSearch.cpp

The Dirichlet noise that is added to self-play games was originally
tuned for a regular UCT search in the AGZ paper. With FPU reduction,
the possibility to discover a noised move is greatly reduced. So
we should not use FPU reduction at the place where we add noise, i.e. at
the root.

Disable FPU reductions at a noised root.

---

scripts/resign_analysis/resign_analysis.py

Add -n argument for prefixes of network names to analyze. This allows
more fine grained analysis of resign percents on a per-net basis, and
it can be used to analyze groups of networks as well.
Also broke up long lines.

Add per-net resign analysis

---

autogtp/Management.cpp
src/FullBoard.cpp
src/GTP.cpp
src/Im2Col.h
src/OpenCL.cpp
src/Random.cpp
src/SGFTree.cpp
src/Training.cpp
src/Tuner.cpp
src/UCTNode.cpp
src/UCTSearch.cpp
src/Utils.cpp

This eliminates all the warnings GCC gives with `-Wold-style-cast` and `-Wzero-as-null-pointer-constant` except where it concerns **cl2.hpp**.

Minimize old-style casts and null pointer constants.

---

training/tf/net_to_model.py
training/tf/tfprocess.py

1. Bugfix: Batch norms weren't being updated.
2. Bugfix: Use 400 batches when recomputing batch norms to reduce error is ~2% (from 13%).
3. Remove the need for external files: SWA is now accumulated in RAM.
4. Change TF restore to be optimistic. This allows restoring from snapshots
that don't have the SWA variable (and vice versa).
NB: I've verified by hand that the batch norms vars are being updated. If I get a little spare time later I'll try and add some unit tests for that.

Clean up the SWA code somewhat.

---

training/tf/tfprocess.py

Backwards compatible batch norm beta support. Replaces zero biases in network file with `beta*sqrt(var + e)` so that the output is correct in leelaz which adds biases before the batch norm.
In my previous test (https://github.com/gcp/leela-zero/issues/785#issuecomment-362274170) it seemed like adding beta gave a very small decrease in loss. Maybe the effect would be bigger when starting from scratch or with bigger learning rate? Even if the strength increase is minor it should be worth it since this doesn't require any additional work in leelaz.
Tested that restoring and saving gives back the input weights. Training gave reasonable loss and output weights and the network works in leelaz. However I don't have resources to do a bigger training run to check how this affects strength.

Batch norm beta support

---

training/tf/net2net.py

The additional weights connecting to the new input planes are filled with normal distribution noise with 0 mean and standard deviation given by the --noise argument. The new planes are added after the existing planes.
The default noise might be little too small but I'm not changing it for this feature. When visualizing the new input plane weights using the script in https://github.com/glinscott/leela-chess/issues/199 gives the following plot:
The network above has 5 new planes.
@alreadydone could you test this?

net2net: Add option to increase the number of input planes

---

src/UCTNode.cpp
src/UCTNode.h
src/UCTNodeRoot.cpp
src/UCTSearch.cpp

- When we expand children nodes, we don't actually create the UCTNode but only keep a proxy of it.
- The actual child node is created (called 'expanded' here) only if it is selected from uct_select_child
- (One more case - for ease of implementation, the root's children are always expanded)
- As of this commit, we saturate around 3.45GB memory footprint when we hit MAX_TREE_SIZE (down from 8.9GB)

UCTNode lazy initialization for memory footprint reduction (attempt 3 of "Reduce the memory consumption of nodes")

---

src/Makefile

Why didn't the CI services catch this?

Add UCTNodePointer.cpp to Makefile.

---

src/UCTNode.cpp
src/UCTNode.h
src/UCTNodeRoot.cpp
src/UCTSearch.cpp
src/UCTSearch.h

This addresses the issue raised in https://github.com/gcp/leela-zero/pull/1082#issuecomment-375688136. It may not appear to be necessary in order to protect the strength of the engine for subsequent moves in a game, but one could imagine this becoming a problem when it's used for analysis.

Allow incremental node expansions.

---

src/UCTSearch.cpp
src/UCTSearch.h

There are complaints that leelaz does not honor the configured time on some corner cases.  This tries to address the problem by:
1) measure time including the 'select new root' code for each move
2) move the tree destructur to the side thread

Reduce time uncertainty

---

src/SMP.cpp
src/SMP.h

If a thread explicitly calls unlock() then the destructor may try to unlock it again.
Check if this Lock instance owns the lock, and attempt unlocking only if it owns it.

SMP : Lock destructor should not unlock mutex if lock is not owned

---

src/NNCache.cpp
src/NNCache.h
src/Network.cpp
src/Network.h
src/Training.cpp
src/UCTNode.cpp
src/UCTNode.h

Instead of keeping a list of std::pair<float,int>, just keep a flat array of floats.  This reduces per-entry NNCache size by half, hence allowing bigger cache sizes for larger playouts.

Netresult memory size optimization

---

CMakeLists.txt
autogtp/CMakeLists.txt
validation/CMakeLists.txt

In large code bases consistency is important. This PR changes all CMake commands to be upper case with the exception of the command `if`.
If these kind of style PRs are welcomed, I would like to submit more to fix the styling of files in `src/`. Eventually I wish to bring in a script like Google's `cpplint.py` as a part of CI to force style checks in all CI runs.

Make CMakeLists.txt file consistently formatted 

---

src/Im2Col.h
src/Network.cpp
src/OpenCL.cpp
src/Tuner.cpp
src/clblast_level3_half/common.opencl
src/clblast_level3_half/xgemm_batched.opencl
src/clblast_level3_half/xgemm_part1.opencl
src/clblast_level3_half/xgemm_part2.opencl
src/clblast_level3_half/xgemm_part3.opencl
src/config.h

Revived the USE_HALF.
The datatypes are fp16 in global memory.  The actual computations are still fp32 because many consumer-grade cards are still not so good at fp16 yet.
Constant number of playouts (4000)
```
50/50 games played
A     B
A leelaz-base       24-26
B leelaz-fp16 26-24
leelaz-base v leelaz-fp16 (50/50 games)
wins              black         white       avg cpu
leelaz-base     24 48.00%       12 48.00%     12 48.00%    505.46
leelaz-fp16     26 52.00%       13 52.00%     13 52.00%    507.16
25 50.00%     25 50.00%
player b: Leela Zero:0.13
player w: Leela Zero:0.13
```
Constant time (10 seconds, 2x GTX1080, 12 threads)
```
50/50 games played
A     B
A leelaz-base       19-31
B leelaz-fp16 31-19
leelaz-base v leelaz-fp16 (50/50 games)
board size: 19 …
```

fp16 datatypes for OpenCL evaluation

---

src/Leela.cpp
src/TimeControl.cpp
src/TimeControl.h
src/UCTSearch.cpp
src/UCTSearch.h

Don't move quickly if we cannot save up time anyway. Can be overruled by
setting --timemanage forced.

Don't use time management if there's no benefit.

---

src/UCTSearch.cpp

Without this, both the debug and Clang builds will fail with undefined reference linker errors.
Another unfortunate miss from the CI checks.

Add definition of UCTSearch::UNLIMITED_PLAYOUTS.

---

src/Network.cpp
src/Network.h
src/Training.cpp
src/Training.h

Network now gathers inputs directly into a vector rather than going via a bitset. The bitset conversion is now only done for the selected move when recording training data. 2nd attempt of #1130 (without other changes).
A couple of questions:
1. My 2nd commit in this avoids `get_scored_moves_internal()` having to be passed the `state` but it looks weird to me that input data has the symmetry applied outside of the function but the outputs are converted back within the function. So:
a. also pull applying symmetry to `result.policy[]` out into `get_scored_moves()`
b. put applying of symmetry to inputs back into `get_scored_moves()`
c. "who cares? you're worrying about nothing"
2. Should `fill_planes()` be a method of `TimeStep` rather than `Training`? I'm not that experienced with OO (I …

Tidy gathering of input vector

---

src/GTP.cpp
src/GTP.h
src/Leela.cpp
src/UCTNodeRoot.cpp

Right now the randomized move selection will still pick moves that only
got a single visit. That means that no matter how badly they are
evaluated, we still have a fair chance of playing them. This means our
learning cycle can't avoid some really bad blunders.
There's some indication that using FPU=parent causes these blunders to
stay happening when ahead, as opposed to the AGZ method of using
FPU=0.5, which ends up filtering them. Because we really want to keep
FPU=parent, filter moves with only a single visit to get a similar
effect, i.e. to not pick moves with a really bad evalution.
This defaults the minimum visits to 1, and also adds a configurable
temperature to move selection, defaulted at t=1.

Exclude low visit moves from random selection.

---

training/tf/tfprocess.py

Add multi-GPU support for training. 
I test the code on a Ubuntu 17.10 with two 1080ti and a similar code is used to train @bjiyxo's 20 block net.
But you will need to use `net_to_model` to convert a net to a model that can be used by the code as the way of getting variables is different.

Add multi GPU training support

---

src/GTP.cpp
src/GTP.h
src/UCTSearch.cpp
src/UCTSearch.h
src/Utils.cpp
src/Utils.h

This is an alternative implementation to #1242 and implements the solution discussed in that thread.
I have added two gtp commands:
```
lz-analyze <interval in centis>
lz-genmove-analyze <color> <interval in centis>
```
lz-analyze will return a multi-line response starting with =\n (or =id\n), before outputting one new info line every <interval in centis>. Each info line has the following format:
```
info <variation 1 info> | <variation 2 info> | .. | <variation n info>\n
```
The variation info has the following format
```
<Move> <playouts> <winrate> <list of moves in variation>
```
Example:
```
info D7 2234 99.94 D7 E6 C4 C3 C5 B3 E7 F7 F6 G6 F5 E4 F8 G7 G8 J7 H8 K6 J8 K8 | C5 260 99.88 C5 C4 D7 D5 E7 C7 C8 B7 B8 B5 R14 Q13 | N3 133 99.94 N3 O3 N2 N1 D7 E7 D5 E6 C4 | S3 120 99.91 S3 C5 …
```

Extend GTP to add support for displaying real time winrates and variations 

---

msvc/VS2015/leela-zero.vcxproj

After reading https://github.com/gcp/leela-zero/issues/1383 and adding the two files manually, build was successful and I saved the project. I hope this file is the only thing neede to fix #1383 but this is my first time using Visual Studio so I am not sure.

Update leela-zero.vcxproj for VS2015

---

src/FastBoard.h
src/FullBoard.cpp
src/FullBoard.h
src/GTP.cpp
src/Network.cpp
src/Network.h

This salvages #1275 mainly to recover the `NUM_SYMMETRIES` constant and get rid of the duplicate symmetry and hash code.

Symmetry cleanup.

---

src/Leela.cpp
src/UCTSearch.cpp
src/UCTSearch.h

Adds support for timemanagement code in leelaz and autogtp that doesn't prune moves and only cuts off the search if the second best move can't overtake the best one with the remaining visits.
The visit distribution with timemanagement is very close to without it and it generates very similar training data. On average less visits are needed per move speeding up the game generation.
More discussion in #1416

Non-pruning timemanagement for self-play

---

training/minigo/convert_minigo.py

Converts minigo weights to work with LZ. Some minigo weights are available here: https://console.cloud.google.com/storage/browser/minigo-pub
Some tests:
LZ weights 147 vs. LZ with minigo weights 303. 1000 visits, minigo weights has 3 handicap stones:
```
lz_minigo_303 v lz_147 (15/100 games)
board size: 19   handicap: 3 (free)   komi: 7.5
wins                  avg cpu
lz_minigo_303      4 26.67%   (black)  945.66
lz_147            11 73.33%   (white)  615.45
```
Minigo vs LZ using the same 303-olympus weights with 100 playouts. LZ arguments: `-g -d -t 1 --noponder -p 100 --timemanage off -r 5`. Minigo used the default settings.
```
lz_303 v minigo_303 (100/100 games)
wins              black         white       avg cpu
lz_303         86 86.00%       42 84.00% …
```

Script for converting minigo weights

---

autogtp/main.cpp

The three conditions are time limit, number of games limit, and console input q+Enter, as implemented by @marcocalignano.
See https://github.com/gcp/leela-zero/issues/1535#issuecomment-399418103.
The `if (true)` condition is added to make it easier to change it to `if (false)`; I have to disable console on Big Red II for some reason.

AutoGTP: allow three quitting conditions simultaneously

---

training/tf/tfprocess.py

This pull request fixes #1502 
The real update operation should be the computation of gradient rather than the assignment of it. I think I made this mistake when merging different branches.
[Some tests](https://github.com/gcp/leela-zero/issues/1502#issuecomment-403891897) are made to make sure the new code can work properly under different settings, but I only test it on my Ubuntu. So maybe you will need to test it on Windows.

Fix #1502 - fix update op of training code

---

src/GTP.cpp
src/GTP.h
src/GameState.cpp
src/GameState.h
src/Leela.cpp
src/NNCache.cpp
src/NNCache.h
src/Network.cpp
src/Network.h
src/OpenCL.cpp
src/OpenCL.h
src/OpenCLScheduler.cpp
src/OpenCLScheduler.h
src/Training.cpp
src/Training.h
src/UCTNode.cpp
src/UCTNode.h
src/UCTNodeRoot.cpp
src/UCTSearch.cpp
src/UCTSearch.h
src/tests/gtests.cpp

Restructured code to remove:
- No global / thread_local OpenCL structures
- Network is now all non-static methods with instance variables
- NNCache is a member of Network, OpenCLScheduler is also a member of Network
- ThreadData is renamed to OpenCLContext (it's no longer thread-specific!)
- Other accompanying fixes

Code restructuring part 1 : no globals

---

.gitignore
autogtp/.gitignore
autogtp/Game.cpp
autogtp/Game.h
validation/.gitignore
validation/Validation.cpp
validation/Validation.h
validation/main.cpp

Fixes #1455.
Also gitignore some local files and outputs.

Add Validation support for specifying GTP commands for each binary

---

src/OpenCL.cpp
src/OpenCL.h
src/OpenCLScheduler.cpp

This fixes a bug introduced during code restructuring, which broke GPU autodetection.

Fix for issue #1632 : resurrect GPU autodetection

---

src/GTP.cpp
src/Network.cpp
src/Network.h
src/Training.cpp
src/UCTNode.cpp
src/UCTNode.h
src/UCTNodePointer.cpp
src/UCTNodePointer.h
src/UCTNodeRoot.cpp
src/UCTSearch.cpp
src/UCTSearch.h

I think that using "score" as a nonspecific term (and not when it, for example, refers to the count at the end of game) makes it unnecessarily hard to understand the code and see how it matches with the literature.

Restrict the use of "score".

---

src/CPUPipe.cpp
src/Network.cpp
src/Network.h
src/OpenCL.cpp
src/OpenCL.h
src/OpenCLScheduler.cpp
src/config.h

Replace F(2x2, 3x3) Winograd transformations with F(4x4, 3x3) transformations that have bigger tile size. F(2x2, 3x3) is theoretically 2.25 times faster than direct convolution and F(4x4, 3x3) is 4 times faster. Transformations are bigger though so in practice the gain is probably not as big.
Benchmarks on GTX 1050 Ti:
```
F(2x2, 3x3) (next):
1600 evaluations in  7.93 seconds -> 201 n/s
F(4x4, 3x3) (This PR):
1600 evaluations in  5.57 seconds -> 287 n/s
```
Batching is much more useful with the larger tile size. There are only 25 tiles on 19x19 board with the larger tile size when there was previously 100. For SGEMM it needs to be padded to 32 tiles so about 20 % of computation is wasted on the padding. With batch size of 4 I get 367 n/s, which would be 80 % faster than the current code. …

Winograd F(4x4, 3x3)

---

src/Tuner.cpp

Fixes #1645. Tuner has 0.5 % error with the previous SGEMM dimensions with 256 channel network but it increases to 1.3 % with the new dimensions required for the new Winograd convolution. The network output seems to be fine even with the larger error so just increase the error limits in the tuner.

Increase error budget in tuner

---

src/GTP.cpp
src/GTP.h
src/Leela.cpp
src/tests/gtests.cpp

Keep a single "network" global in GTP, owned by a unique_ptr and move
things around when needed.

Rearrange network globals.

---

src/GTP.cpp
src/GTP.h
src/Leela.cpp
src/Network.cpp
src/Network.h
src/OpenCL.cpp
src/OpenCL.h
src/OpenCLScheduler.cpp
src/OpenCLScheduler.h
src/Tuner.cpp
src/Tuner.h
src/config.h

This adds --use-half as a command line option, and users can select between fp16/fp32 based on command line.

Runtime selection of fp16/fp32

---

src/SGFTree.cpp
src/SGFTree.h

Fix a bug that an SGF file/string cannot contain
2 consecutive moves of the same color.
Based on pull request #1653.
Fixes issue #1469.

Don't assume alternating colors in SGF.

---

src/config.h

In order to prevent future embarrassments like #1374, make it policy not to have any macro constant unless absolutely unavoidable.

Replace macros with proper constants.

---

src/GTP.cpp
src/GTP.h
src/Leela.cpp
src/Network.cpp
src/Network.h
src/config.h

Runs both precisions for 1 seconds, and if fp16 is faster than fp32 by more than 5%, fp16 is used.
removes --use-half, replaces it with --precision [auto|single|half] option, default auto

Implemented NN eval fp16/fp32 autodetect

---

src/Network.cpp
src/Network.h

The previous method is too strict for fp16 compute. Since lower precision of fp16 is still good enough to play at the same strength as fp32 relax the self check.
Maximum L2-norm error in about 1000 checks for various options using 192x15 network:
| Precision    | Max error |
|--------------|-----------|
| fp32         | 5e-6      |
| fp16_storage | 0.015     |
| fp16_compute | 0.042     |
fp16_compute vs fp32 on Intel(R) HD Graphics Kabylake Desktop GT1.5 using 200 visits with the latest 192x15 network.
```
lz_fp32 v lz_fp16 (131/400 games)
wins              black         white       avg cpu
lz_fp32     62 47.33%       29 43.94%     33 50.77%     93.83
lz_fp16     69 52.67%       32 49.23%     37 56.06%     92.28
61 46.56%     70 53.44%
```
These games were …

Use L2-norm in self check

---

src/NNCache.cpp
src/NNCache.h
src/Network.cpp
src/UCTSearch.h

Should save a tiny bit of memory.

Change policy vector to array.

---

src/OpenCL.cpp

Some OpenCL buffers were allocated too big. Tested with oclgrind that the new sizes are correct.

Fix OpenCL buffer size

---

training/tf/quantize_weights.py

Use smaller precision to store the weights to decrease the file size.

Script for quantizing weights

---

README.md
autogtp/Job.cpp

This reduces data loss in some rare cases(killed process after a continued game), and allows other processes such as LeelaWatcher a chance to load the SGF file.
Not tested as I recently lost my ability to compile autogtp after failing to get my Intel GPU to be default while still allowing my NVIDIA to be used.
Someone, please test this.

Delay deletion of game data of continued games

---

.gitignore
autogtp/.gitignore
autogtp/Game.cpp
autogtp/Game.h
validation/.gitignore
validation/Validation.cpp
validation/Validation.h
validation/main.cpp

Second attempt at #1459 but this time not dependent on Qt 5.6. Instead, each binary argument has to be preceded by "--" (otherwise all GTP commands are sent to all binaries).
Note though that I haven't actually tried building with Qt 5.3.
```
validation.exe -h
Usage: validation.exe [options] [-- binary [--gtp-command...] [-- binary [--gtp-
command...]]]
Options:
-?, -h, --help                    Displays this help.
-v, --version                     Displays version information.
-g, --gamesNum <num>              Play 'gamesNum' games on one GPU at the
same time.
-u, --gpus <num>                  Index of the GPU to use for multiple GPUs
support.
-s, --sprt <lower:upper>          Set the SPRT hypothesis (default
'0.0:35.0').
-k, --keepSgf <output directory>  Save SGF files after each …
```

Add Validation support for specifying GTP commands for each binary (2)

---

CMakeLists.txt
autogtp/CMakeLists.txt
src/GTP.cpp
src/Leela.cpp
src/Makefile
src/Tuner.cpp
src/Utils.cpp
src/Utils.h
validation/CMakeLists.txt

In preparation for uploading this to Debian, I had to tweak a few things relating to installation.
> Can you describe more about how to set ${CMAKE_INSTALL_BINDIR} when building by cmake or make?
`cmake -D` is how you set cmake variables in general.
> Validation can handle other engines than just leelaz, though. And I don't see much risk of autogtp clashing.
Can you suggest a better name for `validation`? For `autogtp` it's still specific to `leelaz` but that's not reflected in the name.
> @infinity0 There is already some works on making Debian package in the “next” branch. See #1445 for reference.
That creates a Debian binary package, which isn't how one gets packages into Debian official repositories (`ftp.debian.org`). I'm talking about the necessary changes to adhere to software …

Packaging improvements

---

src/UCTNode.cpp

Search thread should explore other nodes in this case, this would save
the search from some useless searches.
It has benefit for batching support too. Before this change, all
threads could be busy waiting for the first node being expanded.

Improve MTCS a bit

---

src/Tuner.cpp

Necessary for Clang.
Fixes issue #1809.

Convert string before variadic function call.

---

src/GTP.cpp
src/GameState.cpp
src/GameState.h

As [demanded by GTP](https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html#SECTION00073300000000000000), improving the input handling of `GameState::play_textmove` in the process (which now would crash if given a pass or resignation).

Always expect 2 arguments after "play" command.

---

src/OpenCL.cpp

On many OpenCL implementations, CL_MEM_COPY_HOST_PTR | CL_MEM_READ_ONLY keeps a backing store of the data.  Hence we need to keep two copies of the weight (one on host, one on GPU) spending more memory.
This was done so that the driver can swap in/swap out memory from GPU when GPU memory is in a pinch.  Based on how leela-zero works, I believe this behavior won't help much since we are re-scanning through all the weights every millisecond or so (it will add too much pressure to the PCI-e bus)
So, instead of using CL_MEM_COPY_HOST_PTR, just create a buffer and then copy the weights using enqueueWriteBuffer - saves about 300MB of host memory on a 256x40 weight.

OpenCL : don't initialize weights using CL_MEM_COPY_HOST_PTR

---

src/CPUPipe.cpp
src/Network.cpp

Optimize memory accesses in Winograd transformations. Speeds up initialization with 40 block network by 25%. CPU performance speed up is about 4%. No changes in OpenCL.

Winograd filter transform and CPU in transform optimization

---

src/CPUPipe.cpp
src/CPUPipe.h
src/ForwardPipe.h
src/Network.cpp
src/Network.h
src/OpenCLScheduler.cpp
src/OpenCLScheduler.h

We restructured the code ad moved everything to ForwardPipe.  No need to leave it in the memory anymore.  This saves about half a gigabyte of memory footprint on 20x256 nets

Network : remove unused residual tower weight values

---

src/kernels/convolve3.opencl

Fixes #1837 
Apparently casting doesn't work when the array is global.

Fix vectorized Winograd transform 

---

src/Network.cpp

When doing auto precision detection, make sure prior implementation is destroyed before trying new implementation

Reduce network memory usage when autodetecting

---

.gitignore

When cloning and opening an .sln solution (such as the `/next/` branch) in Visual Studio 2017, the `.vs` folder is created at the base of the project to store temporary user-specific environment settings. By default, Visual Studio 2017's Github plugin instantly detects these as changed files which must be synced. In my case, three files are created:
`ProjectSettings.json - Contains user-set project config settings`
`slnx.sqlite - Contains directory information and other details specific to the user's machine`
`VSWorkspaceState.json - Tracks open files and expanded directory views in the user's workspace`
This minor addition to the base `.gitignore` file resolves this, and as far as I can tell does not ignore any MSVC/VS files which *should* be managed under our git source control.

Update .gitignore to inclue ".vs/"

---

src/NNCache.cpp
src/UCTNode.cpp
src/UCTSearch.cpp

If a node is fully expanded but is reveretd to INITIAL state, there is no chance
it returns to EXPANDED state.  Don't revert nodes to INITIAL state if it is fully
expanded.
Addresses other smaller bugs too
May address #1849

Fixes assert failure on wait_expanded()

---

src/GTP.cpp

Fixes a bug, when number of gpus used was taken from a configuration and 0 was used instead of 1 for auto-detected GPU.

Fix memory estimation for auto-detected gpu.

---

src/GTP.cpp

See discussion in pull request #1642.
This adds an optional side to move in the lz-analyze command, instead
of only a posting interval. This makes the format more consistent with
all other GTP commands.
We check the amount and format of the arguments so we are backwards
compatible with GUIs that send the old format, i.e. with only a posting
interval.

Add side to move in lz-analyze command.

---

src/ForwardPipe.h
src/Network.cpp
src/Network.h
src/OpenCL.cpp
src/OpenCL.h
src/OpenCLScheduler.cpp
src/OpenCLScheduler.h

Rework the Network initialization to pull out the OpenCL benchmarking
for precision autodetection. Add support to ForwardPipe to report
whether it is necessary to run the benchmarks. If the answer is no, and
fp16 compute works, we assume that's what we want.
This avoids the benchmarking overhead on modern AMD cards and probably
on the latest ones from NVIDIA too.

Autoselect half mode for fp16 compute.

---

src/GTP.cpp

Required for GTP compatibility.
Fixes issue #1875.

Don't let printsgf output consecutive newlines.

---

appveyor.yml
msvc/VS2015/cmake_build.bat
msvc/VS2015/leela-zero.vcxproj
msvc/VS2015/packages.config
msvc/VS2017/cmake_build.bat
msvc/VS2017/leela-zero.vcxproj

New AppVeyor jobs are added to build leela-zero by both of cmake and msbuild in Visual Studio 2015 and 2017.
In my local test, there are totally eight AppVeyor jobs that have been passed. The running time of these jobs are listed below:
1. `Image: Visual Studio 2015; Environment: cmake_build=1`: 3 minutes 47 seconds.
2. `Image: Visual Studio 2015; Environment: cmake_build=1, features=USE_CPU_ONLY, run_tests=1`:  3 minutes 17 seconds.
3. `Image: Visual Studio 2015; Environment: cmake_build=1, features=USE_CPU_ONLY USE_BLAS, run_tests=1`: 3 minutes 4 seconds.
4. `Image: Visual Studio 2015; Environment: msbuild=1`: 3 minutes and 26 seconds.
5. `Image: Visual Studio 2017; Environment: cmake_build=1`: 4 minutes and 55 seconds.
6. `Image: Visual Studio 2017; Environment: cmake_build=1, …

Added AppVeyor jobs to build leela-zero by cmake and msbuild in Visual Studio 2015 and 2017

---

CMakeLists.txt

Required on macOS, and probably other platforms.
Fixes issue #1901.

Add GNUInstallDirs include.

---

src/GTP.cpp
src/GTP.h
src/Leela.cpp
src/Network.cpp
src/UCTSearch.cpp

Implement more options in lz-setoption.
Implement a few more parameters that can be set via lz-setoption,
specifically visits, playouts, pondering, resign threshold and the lag
buffer.
We currently don't check the provided values against the reported
min/max values but rely on the UI not to mess up. This could be
addressed in a refactoring. Similarly, commandline and setoption values
should probably treated in a unified way.
Remove the bogus boolean return value from GTP processing functions.

 Implement more options in lz-setoption.

---

src/UCTSearch.cpp

We need to call UCTNode::create_children() even if we aren't expanding due to low memory, because that moves our node's state from INITIAL to EXPANDED.

UCTSearch : fix assert-fail when memory is completely full

---

src/Tuner.cpp
src/Utils.cpp
src/Utils.h

If tuner failed during precision autodetection error output in stdout was read as a GTP message. Hopefully fixes #1932.

Report tuner errors to stderr

---

src/SGFTree.cpp

The sgf size initialized should be same as leelazero program's size settings, so leelazero can open size 9 , size 7 sgf file corretly.

Correct initialize different size sgf

---

src/Leela.cpp
src/OpenCL.cpp
src/OpenCLScheduler.cpp
src/Tuner.cpp
src/Tuner.h

See #1973 
--full-tuner implies --tune-only
--full-tuner requires an explicit precision

Fix for #1973 - full tuner broken for heterogeneous GPUs and auto precision detection

---

src/GTP.cpp

lz-setoption does not work for playouts on leelaz v0.16.
without this patch (I expected about 100 playouts. But I got 11856 playouts.):
$ ./leelaz -g --noponder -w d351f06e446ba10697bfd2977b4be52c3de148032865eaaf9efc9796aea95a0c.gz
Using 8 thread(s).
RNG seed: 14466001740920320255
BLAS Core: built-in Eigen 3.3.5 library.
Detecting residual layers...v1...192 channels...15 blocks.
Initializing CPU-only evaluation.
Setting max tree size to 4324 MiB and cache size to 480 MiB.
lz-setoption name playouts value 100
=
genmove b
Thinking at most 36.0 seconds...
NN eval=0.463478
Playouts: 214, Win: 46.63%, PV: D16 D4 Q16 R4 P3 Q3 P4 R6 F3 C6 D3
(...snip...)
Playouts: 11812, Win: 46.51%, PV: Q4 Q16 D4 C16 E17 D17 E16 C14 O17 R14 Q17 R17
R18 P17 Q18 P16 R16 P18 R15 Q14 K17 R6 S14 S13 S15 P12 O13 O12 …

Fix lz-setoption for playouts.

---

src/Leela.cpp
src/OpenCL.cpp
src/OpenCLScheduler.cpp
src/Tuner.cpp
src/Tuner.h

#1986 has been backed off due to breaking autogtp.  Fix by allowing --tune-only if --full-tune is not enabled.

2nd attempt - full tuner broken for heterogeneous GPUs and auto precision detection #1986

---

src/OpenCL.cpp
src/kernels/convolve3.opencl

Very minor speedup of about 2% with batch size of 1. With batch size of 5 I get speedup of about 5% with half precision and 12% with single precision.
Out transformation memory accesses are almost completely coalesced with the new kernel. In transformation has still very bad memory access pattern when loading the input from memory but I didn't find any improvement to it yet.
With these changes OpenCL backend using batch size of 5 is faster than cudnn with batch size of 32 on my PC.

Optimized out and out_in kernels

---

src/CPUPipe.cpp

The winograd in/out conversion uses constant arrays.  Instead, use hard-coded equations combined with some strength reduction optimizations.  Improves netbench by about 10% on a CPU-only run.

CPU-only eval performance optimization

---

src/kernels/convolve3.opencl

Basically same as #2021.
Use hard-coded equations instead of matrix multiplication.  A 2~3% netbench improvement on my GTX 1080.

Convolve in/out performance optimization

---

validation/main.cpp

by reading its value before the parser is reused. Fixes #2018.

Fixed Validation -k option 

---

README.md

arround 250 hours Tesla V100 computing for free
the doc is here : 
https://docs.google.com/document/d/1DMpi16Aq9yXXvGj0OOw7jbd7k2A9LHDUDxxWPNHIRPQ/edit
General display : 
https://github.com/wonderingabout/leela-zero/tree/azure-cloud-docs
i added computing time in hours for free as an incentive and indication
prices have been stable in the last years so the estimate should stay accurate
these 2 contributors have edit rights on the azure and google cloud docs,
they can also add other people to edit the doc (the people added will have the right to add people too, so better choose them wisely)
@alreadydone 
@roy7

Microsoft azure cloud free trial added (master branch)

---

src/UCTSearch.cpp

(I'm cleaning up my old branches, Feel free to close this as trivial)
There are ~15 usages of `.load()` and ~4 usages of `static_cast<int>(atomic)` this cleans up all but one of them.
The if loop condition seems like it will always be true.

Cleanup atomics and dead if

---

autogtp/Game.cpp
autogtp/Game.h
autogtp/Job.cpp
autogtp/Job.h
validation/Validation.cpp
validation/Validation.h

Engine was added in #1652 as part of allowing Validation to send GTP commands. This change expands the use of Engine to autogtp for consistency and hopefully making it easier for a later change to allow for the server to use GTP commands for self-play and/match games.
I wrote this a while ago and remember doing some quick testing but I haven't had time to go through this as thoroughly as I would like. Especially as I don't want to break autogtp! I decided to make a PR to either help me get back on it or allow someone else to reuse it. So yeah, I'd appreciate any review feedback and suggestions for testing.

Refactor to allow autogtp to use Engine

---

src/GTP.cpp

Generally speaking, providing character pointer as the first argument directly might cause FSB(Format String Bug).
It seems safe without this fix, but I fixed it because it's not recommended style.

Fix printf call style

---

autogtp/Game.cpp
autogtp/Game.h
autogtp/Job.cpp
autogtp/Job.h
autogtp/Management.cpp
autogtp/Management.h
autogtp/Worker.cpp
autogtp/main.cpp

I've cherry-picked some of @amato-gianluca's commits from SAI (I hope that's ok?). Specifically those to allow the server to start self-play games from an sgf (i.e. some of those listed here https://github.com/sai-dev/sai/commits/sai-0.15/autogtp/Management.cpp). I've then extended this to also cover match games.
See https://github.com/sai-dev/sai/issues/7 for a possible use for this in self-play. I think allowing similar functionality for match games could be useful and is a small change, so why not.
If these are accepted as sound enough reasons for including this PR then I'll raise a server issue asking @roy7 for help testing. All I can do and have done so far is get a couple of self-play games (based on existing server responses) and they look like they ran fine. …

Add ability for the server to specify an sgf as the initial position for self-play and match games

---

autogtp/Job.cpp
autogtp/Management.cpp
autogtp/Order.cpp

Allows for the server to optionally add something like this to the JSON for match jobs:
```
white_options : {
playouts : "0",
visits: "1601",
resignation_percent : "5",
noise : "false",
randomcnt : "0"
}
```
No separate hash has been added; I propose that the existing `options_hash` is calculated over both `options` and `white_options` if it is used.
Similar to #2052, I haven't been able to test this. @roy7 do you have any suggestions for how this could be done? I think I remember seeing similar tests done in the past by serving test jobs on a specifically set up test url.

Add optional separate options for white in match game

---

src/GTP.cpp
src/GTP.h
src/Leela.cpp
src/UCTNode.cpp

At 100 visits puct of 0.5 seems to be much better than the default puct of 0.8:
```
lz_puct_0.5 v lz_puct_0.8 (135/400 games)
wins              black         white       avg cpu
lz_puct_0.5     84 62.22%       49 72.06%     35 52.24%     14.82
lz_puct_0.8     51 37.78%       32 47.76%     19 27.94%     15.84
81 60.00%     54 40.00%
```
But puct of 0.5 is not better than 0.8 at 1600 visits:
```
lz_puct_05 v lz_puct_08 (84/400 games)
wins              black         white       avg cpu
lz_puct_05     40 47.62%       16 38.10%     24 57.14%    129.23
lz_puct_08     44 52.38%       18 42.86%     26 61.90%    144.67
34 40.48%     50 59.52%
```
These results suggests that scaling of the `sqrt(n)/(ni + 1)` term in tree search is not correct. I …

Add O(sqrt(log(n))) scaling to tree search

---

src/GTP.cpp
src/Network.cpp
src/Network.h

A possible use case for this would be determining the relationship between komi and winrate without tainting the cache in the process (after komi becomes part of the input with #1825, etc.).

Option to get network output without writing to cache.

---

src/Utils.cpp

Currently Android is treated the same way as everything not-Windows, but this function fails as LZ tries to create the ~/.local/share/leela-zero directory.
There isn't an obvious generic place to use, so defaulting to the current directory as with Windows is probably the safest option.
With this change, the only additions to Leela Zero needed to work on Android are to set up the right compiler toolchain in the Makefile, as discussed at https://github.com/gcp/leela-zero/issues/779.

Fixed leelaz_file on Android

---

autogtp/Management.cpp

Fixes the initial warning:
warning: catching polymorphic type ‘struct Management::NetworkException’ by value [-Wcatch-value=]
} catch (NetworkException ex) {
^~

Fix GCC8 'catching polymorphic type by value' warning

---

src/UCTNode.cpp

Calling get_eval() on zero-visit node will assert-fail.
The original code could assert-fail on b.get_eval() if 'a' and 'b' both had zero visits but suddenly 'a' gained an additional visit.  Suddenly we get to call b.get_eval() with zero visits.

UCTNodePtr rare race condition fix

---

autogtp/Game.cpp
autogtp/Game.h
autogtp/Job.cpp
autogtp/Management.cpp
autogtp/Management.h
autogtp/Order.cpp

Allows for the server to optionally add something like this to the JSON for self-play and match jobs:
```
gtp_commands : [ "time_settings 600 30 1", "komi 0.5", "fixed_handicap 2" ],
```
and additionally optional for match jobs:
```
white_gtp_commands : [ "time_settings 0 10 1", "komi 0.5", "fixed_handicap 2" ],
```
No separate hash has been added; I propose that the existing `options_hash` is calculated over `options [+ white_options] [+ gtp_commands [+ white_gtp_commands]]`.
Also add support for white taking the first move in handicapped job games.
Tested by locally modifying the the JSON inputs for orders to produce both self-play and match games. Confirmed they worked ok and saving and restoring still works.
I did pick up on one existing issue/missing feature that leelaz doesn't parse …

AutoGTP: Allow specifying initial GTP commands. 

---

src/GTP.cpp
src/UCTSearch.cpp
src/UCTSearch.h

This enable me to plot the evaluation across the game
There are other uses of boost::format in the code but I'm open to rewrite this if you prefer something else.
[LZ vs ELF](lz vs 
https://cloudygo.com/ringmaster/minigo-converted-v-elf.games/mg-c-v15-19x19_001005-modeste_v_lz-ELF_V1_d13c40_p1600_99.sgf/)

Add gomill-explain_last_move for additional output in ringmaster

---

src/FastState.cpp
src/FastState.h
src/GTP.cpp
src/GTP.h
src/UCTNode.h
src/UCTNodeRoot.cpp
src/UCTSearch.cpp
src/tests/gtests.cpp

(These instructions have been updated to match the current version.)
The new GTP feature "avoid" specifies moves to avoid. It is implemented as a new argument for the `lz-analyze` and `lz-genmove_analyze` commands.
Syntax is `lz-analyze ARGS [avoid <color> <coords> <number_of_moves>] [avoid ...]` (same for `lz-genmove_analyze`).
The specified coords will not be considered for this color starting from the current move for the next `number_of_moves` of moves. Instead of coordinates, `pass` or `resign` may also be specified.
Example: `lz-analyze 100 avoid b q16,q4,d16,d4 1 avoid w k10 2` forbids Black to play a Hoshi and White to play Tengen for the next move.
An additional form is `allow`. "Allow"ing a list of moves is equivalent to "avoid"ing all other moves, except pass or resign: …

Add a feature to exclude moves from the search.

---

autogtp/Management.cpp
autogtp/main.cpp
src/Leela.cpp
src/Network.cpp
validation/main.cpp

Removed --cpu-only option from USE_CPU_ONLY build and generalised output displayed in cases where potentially referring to a CPU instead of or as well as a GPU.
Fixes #593.

CPU-only option and output fix

---

.gitignore

leela-zero default build directory is `build`.
It is very annoying when using leela as a git submodule that the repository updates whenever it builds.

added: .gitignore: build

---

autogtp/Management.cpp

Self-play games specify `-t 1` for playing which implies batch size of 1, but tuning was done for default settings since number of threads was not specified.

Autogtp: Tune for batchsize 1

---

src/GTP.cpp
src/Leela.cpp

I am not sure if this is the most reasonable fix, but this enables the option to provide zero threads / batchsize to let leela-zero pick a reasonable default.

Regression fix : Addresses #2214

---

src/Tuner.cpp

Parameters are searched in a linear fashion currently. By shuffling them, we will find a good instance more quickly: There should be at most one single better one in the whole second half of the list on average. This means we are allowed to cut the search time in half without incurring a significant subsequent performance penalty.
Also, shuffing could help reduce possible bias due to grouped, similar parameters that affect the environment (e.g. cache, branch predictor, ...), leading to more accurate/fair results.
Additionally, this is a preparation for exiting the tuner during the search, which becomes a possible option.
Disclosure: I take part in computer Go competitions, in which opponents may use Leela Zero. This PR halves the attempted parameters in quick tuning (no change to current …

Shuffle tuner parameters to find good parameters quicker

---

src/GTP.cpp
src/Leela.cpp
src/Network.cpp
src/SGFTree.cpp
src/config.h

In a similar vein to #928, I'm experimenting with various potential komi values on smaller boards. I'd like to be able to set komi in a single place when compiling, the same way I can now set `BOARD_SIZE`, rather than manually editing the `7.5f` literal in a half-dozen places throughout the code.
Seems to work for me, and tests pass (in tag v0.16 at least)

Allow configuring default komi at compile-time

---

autogtp/Management.cpp

Self-play games are still played with batch-size of 1. Larger batch size results in weaker games, but it should speed up the game generation. If the strength loss is small enough compared to speed-up it makes sense to enable it for self-play generation.
Some strength testing against `-t 1 --batch-size=1` with 1600 visits and Dirichlet noise enabled:
```
-t 10 --batch-size=5
lz_205_bs5 v lz_205_bs1 (400/400 games)
wins              black          white        avg cpu
lz_205_bs5    126 31.50%       54  27.00%     72  36.00%    187.08
lz_205_bs1    274 68.50%       128 64.00%     146 73.00%    281.53
182 45.50%     218 54.50%
```
```
-t 6 --batch-size=5
lz_205_bs5 v lz_205_bs1 (400/400 games)
wins              black          white …
```

Enable batching for self-play

---

src/GTP.cpp
src/Leela.cpp
src/Network.cpp
src/SGFTree.cpp
src/config.h

This is a reissue of #2254 because I accidentally opened that one against the wrong branch - sorry!
In a similar vein to #928, I'm experimenting with various potential komi values on smaller boards. I'd like to be able to set komi in a single place when compiling, the same way I can now set `BOARD_SIZE`, rather than manually editing the `7.5f` literal in a half-dozen places throughout the code.
Seems to work for me, and tests pass (in tag v0.16 at least)

Allow configuring default komi at compile-time (next branch)

---

src/GameState.cpp
src/GameState.h
src/SGFTree.cpp
src/SGFTree.h
src/TimeControl.cpp
src/TimeControl.h

-Part of what is described in- Resolves #2097; allowing saving and loading of time control settings to be lossless within LeelaZ.
Note that this only supports "OT" syntax matching output from a printsgf GTP command and currently does not try to save or load remaining time and stones for either side (see https://www.red-bean.com/sgf/properties.html#BL). I'll look at adding that in another commit.
My changes do seem a bit awkward so please do let me know if it can be simplified. Also, if the overtime/byo-yomi syntax is unrecognised, is it reasonable to set up the time control with none? Should a message be printed in this case, and if so, how?
Edit: Added sgf saving and loading of remaining time and stones for both sides.

Added extra support for "TM" and "OT" and other sgf time control properties on printsgf and loadsgf GTP commands

---

src/GTP.cpp
src/GTP.h
src/Leela.cpp
src/UCTNode.cpp
src/UCTNode.h
src/UCTNodePointer.cpp
src/UCTNodePointer.h
src/UCTSearch.cpp
src/UCTSearch.h
src/Utils.cpp
src/Utils.h

Similar to `lcb_max_root` branch by @roy7, but uses normal distribution instead of binomial.
Some tests:
```
15x192 with 1600 visits:
"-g -d -r 5 -v 1600 --noponder -w f438268ef88e083aaf7a08fba885552818abc08cd0aefce9671954a8df3cf707.gz --precision half --timemanage off", "time_settings 0 1 0".
lz_gauss v lz_next (400/400 games)
wins              black          white        avg cpu
lz_gauss    268 67.00%       118 59.00%     150 75.00%     81.32
lz_next     132 33.00%       50  25.00%     82  41.00%     81.26
168 42.00%     232 58.00%
```
```
15x192 with 800 visits:
"g -d -r 5 -v 800 --noponder -w 438268ef88e083aaf7a08fba885552818abc08cd0aefce9671954a8df3cf707.gz --precision half --timemanage off" "time_settings 0 1 0".
lz_gauss v lz_next (400/400 games)
board …
```

Pick chosen move based on normal distribution LCB

---

training/tf/mixprec.py
training/tf/tfprocess.py

Add mixed precision training support. In this method we do all computation in fp16 except loss calculation and the weight update/storage, this will speed up the training procedure and help us use larger batch size.

Mixed precision training support

---

src/Network.cpp
src/OpenCL.cpp
src/OpenCL.h
src/OpenCLScheduler.cpp

Don't autodetect or default to fp32 when all cards have
Tensor Cores. We will assume fp16 is the fastest.
This avoids problems in tune-only mode which does not
detect the precision to use and would use fp32 on such cards.

Don't detect precision with Tensor Cores.

---

src/Leela.cpp

AutoGTP will always send --batchsize, but CPU only
compiles don't support the option. Ignore the option
in those builds.
The same problem exists with --tune-only, but quitting
immediately happens to be sane behavior so we don't need
to fix that.

Ignore --batchsize in CPU only compiles.

---

src/UCTSearch.cpp

It will recursively include OpenCL.h and that
is bad.

Don't include OpenCL scheduler in CPU build.

---

src/GTP.cpp
src/Leela.cpp
src/Network.cpp
src/Network.h
src/SGFTree.cpp
src/Training.cpp
src/Training.h
src/config.h
training/tf/chunkparser.py
training/tf/tfprocess.py

To allow for games to be played with selectable but constant komi.
I have also updated the training data output to change the side to move indication such that it encodes the komi. I haven't tried touching the python code to make use of the komi value during training (I have no way to run it) but have confirmed that the dumped data has no changed when 7.5 komi is used (will also work for -7.5).
Hopefully this will be a small enough change to help start getting #1772 pulled in.
Note that I haven't put any code in to cope with komi being changed mid-game and that data from `save_training` without this change cannot be loaded with the change.
Also I backed out #1618 locally due to #1808, to be able to compile.

Encode komi in the side to move NN input planes
