README.md
Provide step-by-step instructions for compiling on Ubuntu.
=> Update README.md - step-by-step example for compiling on Ubuntu

CMakeLists.txt
Hi this Cmake config works for me what do you think?
=> new CMakeFilelist to compile Leela with cmake (works in Linux)

autogtp/README.md, src/Makefile
Updated Requirements:
QRegularExpression requires Qt5,  https://github.com/vaibhavpandeyvpz/apkstudio/issues/10
=> Update autogtp README.md with apt install command

src/SGFTree.cpp
Per suggestion in https://github.com/gcp/leela-zero/issues/91
Before and after shown in: https://i.imgur.com/S9engJD.png
=> Append prefix of weights to player name in sgf file

autogtp/main.cpp
Example output: https://imgur.com/a/g6jBP
=> print timing information

.gitignore, autogtp/Game.cpp, autogtp/Game.h, autogtp/autogtp.pro, autogtp/main.cpp, autogtp/production.cpp, autogtp/production.h, autogtp/sprt.cpp, autogtp/sprt.h, autogtp/validation.cpp, autogtp/validation.h, src/config.h
Please merge before i get new conflicts!
=> New AutoGTP with multigame support 

autogtp/Game.cpp
This line got duplicated due to one too many rebase ;)
=> autogtp: bugfix remove double color change before move

autogtp/Production.cpp, autogtp/Production.h
Uses picosha2 (https://github.com/okdshin/PicoSHA2) for generating the hash.
Fixes #128
=> Check the network file hash

training/tf/parse.py
=> Training: fix Python docstrings delimiter.

README.md, src/Im2Col.h, src/Network.cpp, src/OpenCL.cpp, src/OpenCL.h, src/config.h, src/half.hpp
=> (Re-created pull request based on next branch) Changed NN in-memory representation from fp32 to fp16

src/FastBoard.cpp
replace O(N^4) algorithm with O(N^2)
also avoid lots of copies.
=> make calc_reach_color faster

src/FastBoard.cpp, src/FastBoard.h, src/FastState.cpp, src/FastState.h, src/FullBoard.cpp, src/FullBoard.h, src/KoState.cpp, src/KoState.h
Most of this code seems to be for Leela to construct complex features which aren't needed by Leela-Zero
Maybe these have value if someone want's to do analysis (like https://github.com/gcp/leela-zero/issues/135) or for future use, but it also has cost (when people try to understand them, reformat code)...
I was waiting for my own analysis and it was a quick and easy PR even if it immediately gets closed working as intended
=> consider removing unused code in FullBoard, FastBoard, FastState, KoState

src/OpenCL.cpp
=> Segfault fix for USE_HALF

autogtp/Results.cpp, autogtp/Results.h, autogtp/Validation.cpp, autogtp/Validation.h, autogtp/autogtp.pro, autogtp/main.cpp
screenshot: https://i.imgur.com/SrU6Dpy.png
I've included a version using sprintf which is more compact and a version using QString.arg which is a little more QT-esque
I've left in my hack to run() which enables this to be tested without playing real games.
=> Competition report

autogtp/Production.cpp, autogtp/Production.h
https://i.imgur.com/X0aQV68.png
=> Add milliseconds per move timing info

autogtp/Game.cpp, autogtp/Production.cpp
Ensures that all options used are visible to clients.
=> Autogtp: Print entire leelaz cmdline

FAQ.md
As title. People here are asking similar questions all the time, I think it'll help them understand the underlying.
Please take a look to see if everything seems to be correct.
=> Add FAQ doc

README.md, src/Makefile, src/config.h
So you don't have to do extra modifications when compiling on MacOS
=> OS auto detection for leelaz compile

scripts/resign_analysis/resign_analysis.py
Improve verbose switch to output which games
were the incorrect resignations.
=> Breakout stats for white/black wins, and overall.

autogtp/Management.cpp
This fixes the problem with 'noise : false'
=> autogtp: fixing default value for any boolean option

autogtp/Game.cpp, autogtp/Game.h, autogtp/Job.cpp, autogtp/Job.h, autogtp/Management.cpp, autogtp/Worker.cpp, autogtp/Worker.h, scripts/resign_analysis/resign_analysis.py, src/GTP.cpp, src/Training.cpp, src/Training.h
Only call it from ProductionJob when --debug dir is used.
This fixes https://github.com/gcp/leela-zero/issues/291
BTW I noticed dump_training is not listed in GTP list_commands. Is this on purpose to hide internal-use commands? Or should we update the list?
=> Create new dump_debug gtp command.

src/Network.cpp, src/Random.cpp, src/TimeControl.cpp, src/Timing.cpp, src/Timing.h, src/Training.cpp, src/UCTSearch.cpp, src/config.h
IMO chrono is much nicer than time_t and #ifdefs
=> Replace timeval and time_t with chrono

autogtp/Game.cpp, autogtp/Management.cpp, autogtp/Management.h, autogtp/Order.h
In case of connection loss, autogtp fallback to the last valid self played configuration and save all the games.
When the connection is reestablished all the saved games are sent to the server.
=> Fallback + resend

src/GameState.cpp, src/GameState.h, src/SGFTree.cpp
Apologies, I missed that has_resigned() actually returned who resigned. doh!
=> Fix resign

autogtp/Game.cpp, autogtp/Job.cpp, autogtp/Management.cpp, autogtp/main.cpp
Merry Christmas to everyone that celebrate!
=> autogtp: reduce verbosity in console output

src/Utils.cpp
Tested with 
make -j4 && echo -e "play black d4\nplay white d5\nfinal_status_list alive\nfinal_score\n7 final_score\naoeu\n7 aoeu" | ./leelaz -w ../weights.txt -g -l util_log |& tee util_tee
=> Util.cpp cleanup

README.md
See https://github.com/gcp/leela-zero/issues/602 feedbacks are welcome.
=> Example for building with macports

src/Network.cpp
=> move rotate_nn_idx in a table

autogtp/Management.cpp
This is not tested because I need the server input to do that but it **should** work.
=> autogtp: support for new option 'visits'

src/GTP.cpp
"place_free_handicap" without specifying a number of stones results in leelaz adding an arbitrary number of handicap stones.
=> Added validation of fixed/free handicap input

Dockerfile
As you wish. Also changed to use gcc instead of clang.
Will try migrating to CMake system later when I have time (will be another PR).
=> Add autogtp to Travis

autogtp/Management.cpp, autogtp/Management.h
I guess this you will like more. The tuning process is also verbose.
=> autogtp: make tuning before starting threads

msvc/VS2015/leela-zero.vcxproj, msvc/VS2017/leela-zero.vcxproj, src/Makefile, src/Network.cpp, src/OpenCL.cpp, src/OpenCL.h, src/OpenCLScheduler.cpp, src/OpenCLScheduler.h, src/ThreadPool.h, src/Tuner.cpp, src/Tuner.h
This is a patch that only takes the Multi-GPU support part from #526.
=> Multi-GPU support

src/FastBoard.cpp, src/FastBoard.h
Second attempt. Rather than try to fix my original repo, I just forked again and redid my change from scratch. Hope it can be merged this time.
=> fix for #679 tiny FastBoad refactor to avoid duplicate code in display_board

src/Network.cpp
=> Fix V matrix size in Winograd CPU convolution

README.md
=> #693 some minor README updates

README.md
As per the observation made [here](https://github.com/gcp/leela-zero/issues/687#issuecomment-359142281) (in #687).
=> Wrong advantaged color

src/UCTNode.cpp, src/UCTNode.h, src/UCTSearch.cpp, src/UCTSearch.h
Fix only version of #711.
Might take awhile to get Travis working so here is the bug fix only.
=> Always copy GameState passed into think or ponder (fix only no gtest)

appveyor.yml
* Use matrix, make code cleaner
* Add exclude files to avoid unnecessary builds
* Run tests under build dir to consistent with Travis
=> Appveyor: Clean up

autogtp/Game.cpp, autogtp/Game.h, validation/SPRT.cpp, validation/SPRT.h, validation/Validation.cpp, validation/Validation.h, validation/main.cpp
It seems that this feature are needed right now.
With this PR validation can:
- accept different `leelaz` binaries 
- accept different options for the `leelaz` binary
- accept different SPRT hypothesis
=> This allow more parameter to validation.

src/GTP.cpp, src/Training.cpp, src/Training.h, training/tf/net_to_model.py, training/tf/parse.py, training/tf/tfprocess.py
Split the dataset into training and validation parts to get better
information about overfitting. Small fixes to timing.
=> Implement real validation split for TF.

autogtp/CMakeLists.txt, autogtp/Console.h, autogtp/Game.cpp, autogtp/Game.h, autogtp/Job.cpp, autogtp/Job.h, autogtp/Keypress.cpp, autogtp/Keypress.h, autogtp/Management.cpp, autogtp/Management.h, autogtp/Order.cpp, autogtp/Order.h, autogtp/Result.h, autogtp/Worker.cpp, autogtp/Worker.h, autogtp/autogtp.pro, autogtp/main.cpp, src/GTP.cpp, src/Training.cpp, src/Training.h
Two new option introduced:
`-t` _n_ run `autogtp` for _n_ minutes and then save the current games on the disk
`-s` run `autogtp` for just one game and exit
Also, in normal with `q+Enter` saves all games on the disk and exit. 
Every time autogtp starts look for previous stored game and restore them.
=> New Stop and resume Feature

src/Network.cpp, src/OpenCL.cpp, src/Tuner.cpp, src/Utils.cpp, src/Utils.h, src/tests/utils_unittest.cpp
sedReplace "lcm" "ceilMultiple"
=> Rename Utils::lcm and add test

src/Network.cpp
Replaces stringstream with faster Boost Spirit X3 parser.
Previously giving invalid weight file caused segmentation fault. The new parser checks for errors.
Benchmark:
```
time ./leelaz -w ../autogtp/257aeeb863dc51bfc598838361225459257377a4b2c9abd3e1ac6cdba1fcc88f -t 1 <<< "exit"
Previous:
real	0m1.004s
user	0m0.876s
sys	0m0.276s
X3:
real	0m0.487s
user	0m0.304s
sys	0m0.248s
```
=> Faster network parsing and error checking

autogtp/Management.cpp, autogtp/Management.h, autogtp/main.cpp
with the he option `-m` _n_ (--maxgames) autogtp stops after _n_ games are completed. `-m` and `-s` are the same thing.
=> autogtp: adding option -m

src/FastBoard.cpp, src/FastState.cpp, src/FullBoard.cpp, src/GTP.cpp, src/Random.cpp, src/Random.h, src/Zobrist.cpp, src/Zobrist.h
* Add a new constant for empty zobrist state,
* Add a new method in Random to getting a uint64_t to cleanup Zobrist init.
* Clean up a warning, some new lines, and a less obvious code pattern
=> Zobrist cleanup

validation/CMakeLists.txt, validation/Results.cpp, validation/Results.h, validation/SPRT.cpp, validation/SPRT.h, validation/Validation.cpp, validation/Validation.h, validation/main.cpp, validation/validation.pro
This will save the results and Sprt data. This won't save the running games.
=> validation: adding Stop Resume feature

autogtp/Job.cpp
=> AutoGTP: Remove sgf files when resuming matches

src/UCTSearch.cpp, src/UCTSearch.h
Avoid making dozens of copies of KoState, avoid copying Gamestate which used to be expensive but isn't anymore.
Some minor fixes that I noticed while making https://github.com/gcp/leela-zero/pull/948
If you don't like these sort of changes feel free to just close this.
=> Cleanups to dump_stats

src/UCTNode.cpp, src/UCTSearch.cpp
I dropped the newline after printing PV
https://github.com/gcp/leela-zero/pull/949/files#diff-70aab7683fe64f9428b8bc47d1d183c0L194
I also included two minor changes I've not managed to fit in elsewhere
=> fix missing newline after PV

src/UCTNode.cpp, src/UCTNode.h, src/UCTSearch.cpp
See discussion and data in https://github.com/gcp/leela-zero/issues/956
=> Remove eval of states without expansion

scripts/resign_analysis/resign_analysis.py
See #971 for example.
Friendly ping @killerducky for review.
=> More concise resign script output

src/OpenCL.cpp
=> Remove unused height variable

src/Leela.cpp
This corresponds to the change to self-play and matches.
=> Update benchmark to -v3200

src/Network.cpp
=> Make ReLU an explicit argument of innerproduct

.gitignore, src/Network.cpp, src/Network.h
Mostly const correctness and auto maximization.
=> Clean up Network.

src/Network.cpp
Instead of telling each thread to run (iterations/num_threads) iterations, Keep a global iteration counter and then share it between all threads.  This results in a more accurate measurement since the previous implementation effectively measured the slowest thread and then multiplied it by the number of threads.
=> Change netbench not to distribute work before running

src/SGFTree.cpp
If the weigths parameter given at command line contains a path the real file name is extracted
=> Leelaz: extract the right SGF player name

training/tf/chunkparser.py, training/tf/net_to_model.py, training/tf/parse.py, training/tf/tfprocess.py, training/tf/v2_write_training.py
(rebased onto next)
1. Add arg parsing to parse.py
2. Switch to using placeholder instead of Dataset for tensorflow batches.
3. Add v2_write_training.py to generate shuffled V2 records.
4. Refactor tfprocess.py
5. Add support for batches larger than GPU RAM size.
=> V2 training

training/tf/net2net.py
=> Fix dropped bias when widening

COLAB.md, Colab.md, README.md
Adds a page with instructions on running autogtp on Google Colaboratory
=> Add COLAB.md and link in README.md

COLAB.md, README.md
Adds a page with instructions on running autogtp on Google Colaboratory
=> Add COLAB.md and link in README.md 

src/TimeControl.cpp, src/TimeControl.h, src/UCTSearch.cpp
* Make fastmove calculation flexible with board size.
See issue #1259.
=> Accelerate the first N moves.

training/tf/net_to_model.py, training/tf/tfprocess.py
=> [Multi GPU] fix split and variable placement error on Windows

src/UCTSearch.cpp
Been a bit busy, but finally got around to this one. Address #1425.
I realized that we have to make a copy of the data since it can change at any time, making sorting difficult if we don't have a copy.  I added a class to store the data. Open to other suggestions.
=> Add order to analysis data

src/SGFTree.cpp, src/UCTSearch.cpp
If the use of different komi is going to be supported, then that should include integral ones, and that means the possibility of draws. I restrained myself however from introducing a contempt factor. :smile:
=> More draw handling.

src/Makefile
=> Suppress upstream warnings in Makefile.

.travis.yml, Dockerfiles/Dockerfile.gpu-half
This is integrated into the main build now.
=> Remove separate USE_HALF build from CI.

scripts/resign_analysis/resign_analysis.py
Added `-R` which performs a binary search.
<details>
<summary>Click to see -h output</summary><p>
```
usage: resign_analysis.py [-h] [-r Resign_thresholds] [-R Resign_rate]
[-v Verbose] [-n Prefix [Prefix ...]]
files [files ...]
This script analyzes the debug output from leelaz
to determine the impact of various resign thresholds.
Process flow:
Run autogtp with debug on:
autogtp -k savedir -d savedir
Unzip training and debug files:
gunzip savedir/*.gz
Analyze results with this script:
./resign_analysis.py savedir/*.debug.txt.0
Note the script takes the debug files hash.debug.txt.0
as the input arguments, but it also expects the training
files hash.txt.0 to be in the same directory.
positional arguments:
files                 Debug data files (*.debug.txt.0)
optional arguments:
-h, --help …
```
=> Added resign analysis option to search for the highest resign threshold that should be set

src/Tuner.cpp
Fix error calculation (Missing batch_size divider).
Better error reporting when no working configuration could be found.
Change reference data to have less rounding errors with half precision.
Replace BLAS reference SGEMM with custom code that gives transposed output like the OpenCL SGEMM.
Fixes issue with too large error when using fp16 compute and 256 channel network: https://github.com/gcp/leela-zero/issues/1689#issuecomment-411060714.
=> Tuner fixes

src/Network.cpp
Tries to fix #1709 - need people to test if it properly falls back to single precision
=> Fall back to single precision net when half precision is broken

autogtp/Job.cpp, autogtp/Management.cpp, autogtp/Management.h
autogtp passes the weights networks in gz format to leelaz upon verification via 'gzip_hash".
=> autogtp: use compressed weights networks

src/CPUPipe.cpp, src/FastBoard.cpp, src/FastBoard.h, src/FastState.cpp, src/FullBoard.cpp, src/GTP.cpp, src/GameState.cpp, src/Im2Col.h, src/NNCache.h, src/Network.cpp, src/Network.h, src/OpenCL.cpp, src/SGFTree.cpp, src/SGFTree.h, src/TimeControl.cpp, src/Training.cpp, src/Training.h, src/UCTNode.cpp, src/UCTNodeRoot.cpp, src/UCTSearch.cpp, src/Zobrist.cpp, src/Zobrist.h, src/config.h, src/kernels/convolve1.opencl, src/kernels/convolve3.opencl, src/tests/gtests.cpp
* Use "vertex" for those in the "letterbox" representation.
* Otherwise, mostly use "intersection".
* Also, capture all possible moves (i.e. including pass) in its own explicit constant.
=> Don't refer to stone locations as "squares".

src/FastBoard.cpp, src/FastBoard.h, src/GameState.cpp
Case-sensitive coordinates are a thing [in SGF](https://www.red-bean.com/sgf/go.html#types), [not GTP](https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html#sec:simple-entities).
=> Isolate and clean up text-to-vertex conversion.

README.md
Required after 73f1f934169a62d7b054aefccecb41029de0fc5f
=> Updated README to compile under Linux with Boost filesystem

msvc/VS2015/leela-zero.vcxproj.filters
=> Adding missing files to msvc 2015 build file

src/kernels/convolve3.opencl
According to @Atarust at #1806 this fixes kernel compilation error with his configuration. No performance difference.
=> Make Winograd matrices global

src/FastState.cpp, src/FastState.h, src/Network.cpp, src/Network.h
This branch contains a few minor changes which, I believe, improve the code quality.
=> The arguments should be const

src/UCTSearch.cpp
Per request at https://github.com/gcp/leela-zero/pull/1772#discussion_r215905542
It's not my original work; the diff was communicated to me by 榜爷 (who operated LZ in Tencent competition).
=> lz-analyze policy prior output

src/Network.cpp, src/Network.h, src/OpenCL.cpp, src/OpenCL.h, src/OpenCLScheduler.cpp, src/OpenCLScheduler.h
Detects cl_khr_fp16 before initializing the nets and then makes the decision on what we want to do
=> fp16/fp32 autodetection, 2nd attempt

src/Network.cpp, src/Network.h, src/config.h
Revive selfcheck for Eigen compilations, plus add self-check even for autodetect cases.
May address #1932 and #1897
=> Fixes for various net initialization issues

src/GTP.cpp, src/GTP.h, src/Leela.cpp, src/UCTNode.cpp
=> Separate FPU-reduction variable for root.

README.md
all in one commit now : 
continuation of : 
https://github.com/gcp/leela-zero/pull/1959
google docs link : https://docs.google.com/document/d/1P_c-RbeLKjv1umc4rMEgvIVrUUZSeY0WAtYHjaxjD64/edit?usp=sharing
=> (AUTOMATED) Google Cloud free trial instructions in google docs with managed instance groups, all in one commit

src/Network.cpp
I'm cleaning up my old branches, Feel free to close this as trivial
=> cleanup loop code

training/minigo/convert_minigo.py
Fix for https://github.com/gcp/leela-zero/issues/2020
After I broke the script by removing conv2d bias in https://github.com/tensorflow/minigo/pull/292
=> Fixed converter script for minigo removing bias

training/tf/quantize_weights.py
see https://github.com/gcp/leela-zero/issues/2107#issuecomment-451390081
=> update quantize_weights.py with round  some numbers to 2 digits  reduce weight file size

autogtp/Game.cpp, autogtp/Game.h, autogtp/Job.cpp
Follow up to #2078 and #2096 to include full engine options and starting GTP commands are in sgf comments.
=> AutoGTP: Added full engine options and starting GTP commands to sgf comments

src/OpenCL.cpp, src/OpenCL.h, src/Tuner.cpp, src/Tuner.h, src/kernels/clblast/hgemm_tensorcore.opencl, src/kernels/tensorcore_test.opencl
See #2036 for details.  ~10% performance gain on a V100 cluster.  Validated that doesn't lose strength on equal playout (vs. current next branch)
=> Tensor Core support with PTX inline assembly

src/GTP.cpp, src/GameState.cpp, src/GameState.h
Added the following GTP commands.
last_move
move_history
The output of these commands match the corresponding commands in GnuGo.
=> Added several simple GTP commands useful for building interfaces to LZ

training/elf/elf_convert.py
This was merged into leela-zero/next in https://github.com/leela-zero/leela-zero/pull/2213
it should have been merged to the master branch as it's doesn't affect the client code and doesn't require staging/releasing.
=> small tweak for ELF v2 weights

src/UCTNode.cpp
=> Ignore passing moves unless they make sense.

src/UCTSearch.cpp, src/UCTSearch.h
=> Report root visits in gomill-explain_last_move.
